<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>afdad93f-d362-442c-b58d-2bb88b665ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.is-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Your session has ended. Please log in again.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52ec7d69-a0d0-411a-86b3-586e8f0665fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>modal-button-confirm</value>
      <webElementGuid>104f7c6b-a7f2-4575-a18e-a72cfa4c1f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-danger</value>
      <webElementGuid>a074d694-de7b-40c1-a4ea-cdf8579495e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OK </value>
      <webElementGuid>235a0eed-f601-47f1-9d00-c981aa54f5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;modal is-active&quot;]/div[@class=&quot;modal-card&quot;]/footer[@class=&quot;modal-card-foot is-justify-content-end&quot;]/button[@class=&quot;button is-danger&quot;]</value>
      <webElementGuid>2580d24d-ee07-4ba0-8537-ec1ea6e18485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your session has ended. Please log in again.'])[1]/following::button[1]</value>
      <webElementGuid>535db8cb-d3c3-4281-bce8-d630febb3a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning:'])[1]/preceding::button[1]</value>
      <webElementGuid>e3a51579-a5f3-4e40-a2e2-223303a5f790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[1]</value>
      <webElementGuid>af1d7260-44ff-4643-b44d-861b1052e666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>a250dbc7-36ad-4acd-ba05-e34aa878207d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' OK ' or . = ' OK ')]</value>
      <webElementGuid>c6e0ec59-6d7b-47fc-8943-26dfa7c9f514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
