<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add  Location</name>
   <tag></tag>
   <elementGuidId>68b2d71f-7b03-49f3-834c-48bf6453f1be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.is-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[5]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6736fb8-969e-4a61-ac6a-583297d5f56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-primary</value>
      <webElementGuid>c258baf6-2275-4a12-822a-c86bc9607d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add  Location</value>
      <webElementGuid>bd7df8ba-e5d6-4450-ac3b-727d354bc132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;array box loc not-column&quot;]/div[@class=&quot;level mt-1&quot;]/div[@class=&quot;uploader level-right&quot;]/div[@class=&quot;buttons&quot;]/button[@class=&quot;button is-primary&quot;]</value>
      <webElementGuid>2428c231-7638-4af8-9849-c7df209d6f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/button</value>
      <webElementGuid>42c7104d-e77a-4f7b-9b75-8d65ed746633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[2]/following::button[1]</value>
      <webElementGuid>00292b89-d48f-41e5-86d7-ceff17062664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download template'])[1]/preceding::button[1]</value>
      <webElementGuid>25a0d9c2-eff7-41c9-9ac6-1ebb92f0f3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button</value>
      <webElementGuid>1ca60fef-a9cd-4d17-8561-12b2e472bba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add  Location' or . = 'Add  Location')]</value>
      <webElementGuid>8aaf69df-6056-4d70-86e9-ee556a49aa25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
