<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_21</name>
   <tag></tag>
   <elementGuidId>42fec0a9-2e49-4996-8241-0b3e9850174e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[4]/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d7f6c51-4884-4c1d-a0e1-443927ead972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9233bf0-7b60-488a-9d58-52319881bb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>537229dc-c186-4f6d-ba4f-059dc6554e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>492aed8e-8ccd-4bbb-8d44-f1c3af9c0fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>selectable-date-cell</value>
      <webElementGuid>bf5ed139-19c1-427f-b64a-15d0a6def2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-cell is-selectable</value>
      <webElementGuid>6475e736-ab6b-4094-9279-9184ed60a9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0284e0c2-b78c-4490-ac01-df3ebbc71f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exULELPane horizontal&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;array box exULELArray column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-1&quot;]/div[@class=&quot;card-content not-columns&quot;]/div[@class=&quot;card is-paddingless group carrierInfo vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;group line3 horizontal&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;field-container exULELEffDate column&quot;]/div[@class=&quot;field schema-field&quot;]/div[@class=&quot;b-tooltip is-primary is-bottom is-medium is-multiline maybe-tooltip&quot;]/div[@class=&quot;tooltip-trigger&quot;]/div[@class=&quot;datepicker control is-small&quot;]/div[@class=&quot;dropdown dropdown-menu-animation is-bottom-right is-active is-mobile-modal&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;dropdown-content&quot;]/div[@class=&quot;dropdown-item&quot;]/div[1]/div[@class=&quot;datepicker-content&quot;]/section[@class=&quot;datepicker-table&quot;]/div[@class=&quot;datepicker-body&quot;]/div[@class=&quot;datepicker-row&quot;]/a[@class=&quot;datepicker-cell is-selectable&quot;]</value>
      <webElementGuid>0b6f973b-2fb7-4499-9ca2-530b77b5944c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[4]/a[5]</value>
      <webElementGuid>df20e53a-3e6a-4db2-83c0-7b54fdfc17cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[14]/following::a[21]</value>
      <webElementGuid>257e2db4-5fdb-48f4-b9ed-218ff302ace9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[7]/following::a[21]</value>
      <webElementGuid>adeecd42-11b2-4d23-8111-8066597c169e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[4]/preceding::a[11]</value>
      <webElementGuid>9f4e6538-8e1e-44d5-b7da-2154be1d98c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[213]</value>
      <webElementGuid>6278ff93-9860-4540-bb68-594cf914f33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[4]/a[5]</value>
      <webElementGuid>f25104b2-4da7-4eca-82d0-108268c9a488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '21' or . = '21')]</value>
      <webElementGuid>62735193-99df-4b1e-bf7e-c6001633ae6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
