<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_30</name>
   <tag></tag>
   <elementGuidId>d3e6ff61-2034-4527-a0fc-c6ea2f806939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div[2]/div/div[5]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[5]/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52d17250-1819-47ae-933d-8ce6caf0a101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a569ced-3be3-40d9-83fb-6a7a23b70f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>66b0123f-86d2-40f8-bbf3-e5970716ca08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9dc683cf-b0ef-49ab-b64d-409af701c7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>selectable-date-cell</value>
      <webElementGuid>c02c78e8-8c1f-41f3-bf6c-dec16a39af83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-cell is-selectable</value>
      <webElementGuid>b3cf6c57-5dc8-4a1f-b96f-f4c4c7922a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6d3ba630-7a2d-45ef-8dae-5bc778784fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exULGLPane vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;array box exULGLArray not-column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-1&quot;]/div[@class=&quot;card-content not-columns&quot;]/div[@class=&quot;card is-paddingless group exCarrierInfoCard vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;group exCarrierInfoLine horizontal&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;field-container exULExpDate column&quot;]/div[@class=&quot;field schema-field&quot;]/div[@class=&quot;b-tooltip is-primary is-bottom is-medium is-multiline maybe-tooltip&quot;]/div[@class=&quot;tooltip-trigger&quot;]/div[@class=&quot;datepicker control is-small&quot;]/div[@class=&quot;dropdown dropdown-menu-animation is-bottom-right is-active is-mobile-modal&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;dropdown-content&quot;]/div[@class=&quot;dropdown-item&quot;]/div[1]/div[@class=&quot;datepicker-content&quot;]/section[@class=&quot;datepicker-table&quot;]/div[@class=&quot;datepicker-body&quot;]/div[@class=&quot;datepicker-row&quot;]/a[@class=&quot;datepicker-cell is-selectable&quot;]</value>
      <webElementGuid>63270286-275f-4993-99d8-14621c298152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div[2]/div/div[5]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[5]/a[7]</value>
      <webElementGuid>d68e01e7-fa6a-4755-b27f-21179299f10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[4]/following::a[30]</value>
      <webElementGuid>8d95f30b-e1d9-4f8d-82b1-ef7bfd8364a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::a[30]</value>
      <webElementGuid>7cc90f95-53ac-4d64-ac70-061259cd0149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GL Coverage Limits:'])[1]/preceding::a[2]</value>
      <webElementGuid>4fee1f36-12b3-4bd5-89c9-ccd04a17014c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Each Occurrence Limit*'])[1]/preceding::a[2]</value>
      <webElementGuid>6f278d4e-e683-4830-8465-7ef9457d6da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[65]</value>
      <webElementGuid>14d28e29-5c60-4ddb-af95-ef7967922846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div[5]/a[7]</value>
      <webElementGuid>81006578-2ef3-40fc-befe-c4fd6869c8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '30' or . = '30')]</value>
      <webElementGuid>4425e1c3-a707-4ea0-990b-e30fd47e9e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
