<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Re-Rate</name>
   <tag></tag>
   <elementGuidId>4b62265e-4339-4f69-b4fc-b1e1ac6f4fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.is-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[3]/div/div/div/div[5]/div/div/div/div[8]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a20aee18-e5dc-4035-8994-adf7ddef0ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-primary</value>
      <webElementGuid>1c7820aa-e524-425e-9d9e-8d18f9ee6291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Re-Rate</value>
      <webElementGuid>3af93a05-c612-46ad-91e8-c2325ad8f482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exRating vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;card is-paddingless group exLayerCard vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;group exRerateButtonLayer horizontal  has-text-centered&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;field-container exRerateButton column is-primary&quot;]/div[@class=&quot;field schema-field&quot;]/a[@class=&quot;button is-primary&quot;]</value>
      <webElementGuid>303bbe7a-46dd-44d3-b2d9-3382a26a5be0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div[5]/div/div/div/div[8]/div/div/div/a</value>
      <webElementGuid>cfacc1da-5488-4aeb-bd53-331e6f18d34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Re-Rate')]</value>
      <webElementGuid>7ecf1c5c-04c1-4606-99f6-75a18511ecbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead XS/UM'])[1]/following::a[1]</value>
      <webElementGuid>6676d782-7eed-4a17-b7da-8e20d07c7127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In order to proceed you have to Re-Rate'])[1]/preceding::a[1]</value>
      <webElementGuid>cef16317-3d0a-4e36-a4a3-6eee6e5a599e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prorata Factor'])[1]/preceding::a[1]</value>
      <webElementGuid>912534e3-0094-49fc-bee3-5d150a961950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Re-Rate']/parent::*</value>
      <webElementGuid>e1a817ec-8e42-438f-9234-d4c24922708b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/a</value>
      <webElementGuid>10d5e498-0d2f-48b7-9399-8bbb192d97c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Re-Rate' or . = 'Re-Rate')]</value>
      <webElementGuid>aaa73177-b93f-4c75-960f-ea89e04ce331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
