<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_exULGLArray_0_exULExpDate</name>
   <tag></tag>
   <elementGuidId>b184c8d4-9326-4214-9e35-b4013e251f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULExpDate-1072-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULExpDate-1072-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a6d3428-b419-481c-a919-84e37e02c2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35842c0c-800d-47b0-9f27-8261bab3e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25c0c589-07a0-4d01-b050-3ff835824616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>1be49379-fb49-47cc-bd04-03b84ba7b350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULExpDate-1072-0</value>
      <webElementGuid>0e94e045-237b-435f-8e31-6bbe4affe725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exULExpDate</value>
      <webElementGuid>1f4ee0bf-66f9-4f37-aa2c-ae81bd795f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>db43da7d-e7a6-47db-b898-71b2e4526c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULExpDate-1072-0&quot;)</value>
      <webElementGuid>17e2536e-ed25-45f5-aada-d2041ddcb589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULExpDate-1072-0']</value>
      <webElementGuid>3be71ad7-8108-4f63-af63-2b2792cce87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div[2]/div/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>442ce419-d93d-49f5-9f84-96efe8626732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>257b1580-bef6-4610-8a3d-932ef99744c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULExpDate-1072-0' and @name = 'exULGLArray_0_exULExpDate']</value>
      <webElementGuid>3604446b-7e43-4e22-97b8-6ef2c08eb98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
