<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Name_exULELArray_0_exELCarrier</name>
   <tag></tag>
   <elementGuidId>61ff75ad-7726-46be-98d5-8a099f1a1b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exELCarrier-1238-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exELCarrier-1238-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f12734-d3a8-478b-8c2c-b5eea1695b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exELCarrier-1238-0</value>
      <webElementGuid>772b1db5-a526-41cd-b0a8-f13365c6417e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exELCarrier</value>
      <webElementGuid>e8106787-5b45-4ed4-b634-dd4c839fedbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exELCarrier-1238-0</value>
      <webElementGuid>a19b3ef0-3575-4448-9f61-04064531cfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>cef4b54a-0af1-4662-be26-c6e3a70c7fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exELCarrier-1238-0&quot;)</value>
      <webElementGuid>bd953af2-bb7c-452c-b3e9-0e5b7ea98bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exELCarrier-1238-0']</value>
      <webElementGuid>25c658f3-4f8a-4bb9-aa8f-a975d7772739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>0a8df0f7-a86d-4c30-ac8f-07aae3def16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>27efef4a-9295-4706-b6a2-6a7982aa8b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exELCarrier-1238-0' and @name = 'exULELArray_0_exELCarrier']</value>
      <webElementGuid>fe8acec8-e5d1-4c61-98c3-aa27ea292da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
