<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vehicles_exULALArray_0_exALLocation_0_a456aa</name>
   <tag></tag>
   <elementGuidId>88fb5665-3e8b-4d75-851b-d9b66a82fa59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exALExposure-1150-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exALExposure-1150-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>074b3777-ffa4-4662-a95c-221c6fea1fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b016401f-d2e6-407d-82f2-decc57f0b054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3eb7af87-b653-4cfc-b2ea-61d9a3ce33ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exALExposure-1150-0</value>
      <webElementGuid>e29f99ac-61fb-4264-b45f-52941ca544d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_0_exALExposure</value>
      <webElementGuid>72cfd848-48c2-4574-8788-ed5c12376ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0919c45a-9fd6-417b-bc70-73b21adbe3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>86da3397-4d3f-475d-92a3-cb0ecc440ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exALExposure-1150-0&quot;)</value>
      <webElementGuid>6bc98b68-9928-493f-bc6d-53fad3cd76f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exALExposure-1150-0']</value>
      <webElementGuid>f8a9d959-f0b4-4236-a85f-e24e91b485a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div/div[2]/div/div/div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>8a75a10c-1456-4250-b557-d52529e10088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div[2]/div/div/div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>ada52fa4-0c06-4ed7-b59f-28474502875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exALExposure-1150-0' and @name = 'exULALArray_0_exALLocation_0_exALExposure' and @placeholder = '#']</value>
      <webElementGuid>0dcd6975-cc99-4100-9a39-513f579ac1de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
