<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Experience_experience</name>
   <tag></tag>
   <elementGuidId>cc53e3f0-2f93-4376-8085-c016b4348606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-experience-1199</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-experience-1199']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69b5a126-4097-4e38-9ca8-5286104c4452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-experience-1199</value>
      <webElementGuid>99899b2c-3f36-419b-aaa7-b7fc3f87d20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>experience</value>
      <webElementGuid>a98f71bf-c2ac-4a95-91a3-a2ef2832543d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-experience-1199</value>
      <webElementGuid>112449ae-63dd-47c2-bf85-28f6d35f7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>924f618a-49eb-4f9a-a46a-f8c8275cb48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-experience-1199&quot;)</value>
      <webElementGuid>c5b4bbf1-b542-4090-9b1f-cca509daaf9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-experience-1199']</value>
      <webElementGuid>cf23802a-164d-4a21-ad5a-3d703dd0ea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[14]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>a83b4ee5-e5dd-40df-9204-c9af3815c718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>aa2bc0a2-1bf7-4bc7-bcbc-dd6e4c6e601d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-experience-1199' and @name = 'experience']</value>
      <webElementGuid>914c0ede-ed87-4aa5-836f-79d601ecddac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
