<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quote_exULELArray_0_exULELQuoteNum</name>
   <tag></tag>
   <elementGuidId>5da2aadc-5842-44c2-9b89-1632ca99f68a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULELQuoteNum-1239-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULELQuoteNum-1239-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4de2c82d-7d99-450a-949f-55864ab36b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULELQuoteNum-1239-0</value>
      <webElementGuid>a615364e-0988-458d-8dd6-f261b2aed159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exULELQuoteNum</value>
      <webElementGuid>da658653-6d99-44af-bd04-eaf59c7a212f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exULELQuoteNum-1239-0</value>
      <webElementGuid>10b581a3-08c3-4454-b5c9-11cca74f8069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>9e92125c-5878-4e75-aebd-97afcb1624aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULELQuoteNum-1239-0&quot;)</value>
      <webElementGuid>07dca77c-23ae-41ca-a7bd-58481fa053c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULELQuoteNum-1239-0']</value>
      <webElementGuid>57711ba1-9305-4606-be40-0013677764b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>df68b51e-9e63-4ac6-b522-66b77cda8b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>6a7b4e27-e8e5-49d0-88d8-650474525ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exULELQuoteNum-1239-0' and @name = 'exULELArray_0_exULELQuoteNum']</value>
      <webElementGuid>3d66e9d3-aba1-47a4-ad7e-49bc483a4691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
