<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commercial Excess Liability Declarati_cbf8c2</name>
   <tag></tag>
   <elementGuidId>df9698bc-d367-4dba-93ad-b8f2b0c1e914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='UGLX 5055 SI'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>561c36dc-090f-4068-a9a0-0d4ffb835fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a7310f85-2cd8-4b1e-a614-befda7f032ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fd10e810-f69d-476e-9f82-b5596d745417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UGLX 5055 SI</value>
      <webElementGuid>4d591b9e-2061-4d5c-afdc-06683849428e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07f8d0ee-ef7b-4faf-b195-f502590d42a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UGLX 5055 SI</value>
      <webElementGuid>4b9cdf9e-7d97-472b-a1ab-3115e1951aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forms-table&quot;)/tbody[2]/tr[4]/td[1]/label[@class=&quot;checkbox small&quot;]/input[1]</value>
      <webElementGuid>fd629e8a-d8b7-4591-ae14-62377d805d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='UGLX 5055 SI'])[2]</value>
      <webElementGuid>3ce0885e-ca86-4e89-8e9b-5ecbc39d266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='forms-table']/tbody[2]/tr[4]/td/label/input</value>
      <webElementGuid>738c2f9f-8d4b-4a19-bf4e-a70355bee7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr[4]/td/label/input</value>
      <webElementGuid>48772091-b6e1-4ec0-8b9a-6a55c307503e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'UGLX 5055 SI']</value>
      <webElementGuid>d07d34ba-421b-422c-9caa-aecdd27067f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
