<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_exULELArray_0_exULELEffDate</name>
   <tag></tag>
   <elementGuidId>35db03b8-32fc-4ca8-a662-44f1664b6956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULELEffDate-1241-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULELEffDate-1241-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a00faa66-c082-4136-9d21-1c2a51986148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1dc5b022-2bda-4f7f-af7b-febbdcd3c153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bfa62757-b345-408f-9a44-34f687f6f6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>0081ddf7-3819-447c-a665-63bf4c65761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULELEffDate-1241-0</value>
      <webElementGuid>65752be0-8fc8-42d6-96d5-80a3ab4f099c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exULELEffDate</value>
      <webElementGuid>986e1215-5a5f-4c98-867b-4dce46b093e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>6e5db14b-a2ad-4d07-89da-a51b83c69f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULELEffDate-1241-0&quot;)</value>
      <webElementGuid>73d7c9bf-4c9b-41c3-80ab-bab37a30a40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULELEffDate-1241-0']</value>
      <webElementGuid>3bdeec03-b25e-4295-baa7-de270604d733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d93b18f0-ba43-484e-9b1b-525477160e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e8361af0-1fa9-40f0-9a7e-ab9313a05702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULELEffDate-1241-0' and @name = 'exULELArray_0_exULELEffDate']</value>
      <webElementGuid>48b67acc-e060-4102-b3d7-89c760f7134d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
