<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy_exULEBLArray_0_exULEBLPolNum</name>
   <tag></tag>
   <elementGuidId>03b644f9-c23e-4cc1-ab0c-cf48a65c6b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULEBLPolNum-1231-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULEBLPolNum-1231-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83678a61-84b3-4636-b5f0-7044a967def1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULEBLPolNum-1231-0</value>
      <webElementGuid>15938668-6201-4b3c-ac3e-04a05a7b6a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULEBLArray_0_exULEBLPolNum</value>
      <webElementGuid>8f07967e-360a-4707-926d-32cbf7c4557e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exULEBLPolNum-1231-0</value>
      <webElementGuid>741c8451-e32f-4876-b6f8-8c3c998412a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>40ae18e9-c545-47af-9610-4cc7189c3abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULEBLPolNum-1231-0&quot;)</value>
      <webElementGuid>12427de7-ec53-4a1e-9e5b-be30abf05b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULEBLPolNum-1231-0']</value>
      <webElementGuid>d66f8390-85cf-49d0-a54e-e4f6e5fb5c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>b0159d0a-21d3-4234-b056-7628bcadf8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>46bb7d94-19cb-416c-a470-824064bc58bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exULEBLPolNum-1231-0' and @name = 'exULEBLArray_0_exULEBLPolNum']</value>
      <webElementGuid>d2652144-6671-4a34-a5d1-f2e07181e739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
