<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Underlying GL Premium_exULGLArray_0_e_8ede46</name>
   <tag></tag>
   <elementGuidId>2b52d8bd-4ba0-4575-8001-2d8fe3d99bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exGLUnderlyingPremium-1098-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exGLUnderlyingPremium-1098-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>266f3342-bf3c-4881-ae16-e7e37bcc5d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>458455d3-73ba-4923-a1da-e29fc1d780fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>eb6db8c9-6f55-47c1-9bd7-6204389595a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exGLUnderlyingPremium-1098-0</value>
      <webElementGuid>edb3ec20-6b6e-4135-b709-5f71b33fc100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exGLUnderlyingPremium</value>
      <webElementGuid>df0ee49d-b2fd-4e90-9733-285bdc75b476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>75f609e7-071d-4169-9eb8-a4bc7c59faa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exGLUnderlyingPremium-1098-0&quot;)</value>
      <webElementGuid>0f0f9b6f-63db-434e-8070-f276ba9aaa1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exGLUnderlyingPremium-1098-0']</value>
      <webElementGuid>6d54faf5-e750-44bc-8569-5a4be759c793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[7]/div/div[7]/div/div/div[2]/div/input</value>
      <webElementGuid>afca5ef9-1e2f-4f06-b4a7-8a303e321cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/input</value>
      <webElementGuid>e4539180-58ad-4ef9-aaeb-b19cc979da7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exGLUnderlyingPremium-1098-0' and @name = 'exULGLArray_0_exGLUnderlyingPremium']</value>
      <webElementGuid>d38d358a-6a7a-4d0d-9c98-7d5624711232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
