<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commercial Excess Liability Coverage _1a36df</name>
   <tag></tag>
   <elementGuidId>a64a6146-881a-492a-9a1f-7d37bedea27e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;UGLX 5007&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='UGLX 5007']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>feac15f0-a615-4ae0-9f80-6841a7b32f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7e517296-d805-450e-aab2-a5c266ec7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>27a68c5f-7343-41b7-a2c6-c5b72ea11a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UGLX 5007</value>
      <webElementGuid>4d8b942f-ddbd-4f01-8994-7f11d28d82cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06eb4106-8ea7-477e-92f9-fab29ae03018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UGLX 5007</value>
      <webElementGuid>776a7e19-574c-4fe7-81ca-dea0d57b5f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forms-table&quot;)/tbody[2]/tr[6]/td[1]/label[@class=&quot;checkbox small&quot;]/input[1]</value>
      <webElementGuid>2db6f894-fa1f-4b34-97ba-aa3de14777bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='UGLX 5007']</value>
      <webElementGuid>7d5e1fe8-e492-4285-820e-d7a61e3e3532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='forms-table']/tbody[2]/tr[6]/td/label/input</value>
      <webElementGuid>53c20b90-2733-479e-aafe-021d0d1a90f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr[6]/td/label/input</value>
      <webElementGuid>2dd48ef7-fd19-41dc-8426-644cbf8ee53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'UGLX 5007']</value>
      <webElementGuid>d4860fc4-be80-45e8-8b21-cc8e9d3166b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
