<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_loc_1_locStreet</name>
   <tag></tag>
   <elementGuidId>dc04bce9-b357-46d1-93c2-e48716c5ec6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-locStreet-172-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-locStreet-172-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85ae23fc-edd4-4b76-afe1-50534d2d05df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-locStreet-172-1</value>
      <webElementGuid>45d54856-2198-4b4b-a98e-5d581d668ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loc_1_locStreet</value>
      <webElementGuid>4f5d91f7-ffb3-4a15-8ade-fac88c52bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-locStreet-172-1</value>
      <webElementGuid>30854724-5cb3-4d92-9471-3c89a516cccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>d714ba1a-91c7-480b-8a25-6103235ce23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-locStreet-172-1&quot;)</value>
      <webElementGuid>92d0e74c-c862-4bae-96e4-dc73e28d87ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-locStreet-172-1']</value>
      <webElementGuid>986e4f13-d3d6-4a46-a141-0277cf0c48d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div[3]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a54f109c-a068-4cce-8c93-eecd15c33d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>d6f51269-e304-4153-9058-9141c8371405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-locStreet-172-1' and @name = 'loc_1_locStreet']</value>
      <webElementGuid>e864aac0-6ce0-4521-8901-31ac57d840c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
