<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exclusion - ProductsCompleted Work Ha_b8aa9f</name>
   <tag></tag>
   <elementGuidId>db6f9194-6efb-416c-afea-229a7f2c3d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;UGLX 5080&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='UGLX 5080']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ad3834d-5ef0-4104-8cd4-b23f8f937c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b119416-0f28-4399-baf2-ca49ae67d873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>53e7df60-5ab4-466e-8ba2-01d75291d2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UGLX 5080</value>
      <webElementGuid>386a6d2e-6d4f-4ac1-93d1-6e62b654b5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>235d0700-82e9-48ac-9c61-e4681f740ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UGLX 5080</value>
      <webElementGuid>15b32c30-75af-4172-8593-a60d6e6ba62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forms-table&quot;)/tbody[2]/tr[7]/td[1]/label[@class=&quot;checkbox small&quot;]/input[1]</value>
      <webElementGuid>8bebe4d0-4571-4d36-931e-79d8ce630706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='UGLX 5080']</value>
      <webElementGuid>d2593f1d-16c1-4b5e-96ca-25221042dd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='forms-table']/tbody[2]/tr[7]/td/label/input</value>
      <webElementGuid>b92d7535-572e-434b-b09a-1f09e6e961c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr[7]/td/label/input</value>
      <webElementGuid>40b039c0-3906-4e07-82f1-1b1f63921e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'UGLX 5080']</value>
      <webElementGuid>cb0ae2c0-ae11-4eab-911e-ec4d55993db0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
