<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PolicyQuote Number_exULGLArray_0_exUL_e9ff26</name>
   <tag></tag>
   <elementGuidId>9378ce8a-f6ab-4a48-81ef-59fa19b07217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULPolQuoteNum-1045-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULPolQuoteNum-1045-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36694d08-73d1-4b35-a571-a399750bff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULPolQuoteNum-1045-0</value>
      <webElementGuid>ae13faeb-ee74-4c8e-97b5-cf1b4288f418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exULPolQuoteNum</value>
      <webElementGuid>a72d569e-316a-4c66-818a-04191b88f9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exULPolQuoteNum-1045-0</value>
      <webElementGuid>50543552-b7f7-428d-8db3-aa2da02d9c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>41454328-acb0-4d3e-b6af-8ebe7874d46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULPolQuoteNum-1045-0&quot;)</value>
      <webElementGuid>23050423-da41-4803-b2a7-d1bd60b6f6c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULPolQuoteNum-1045-0']</value>
      <webElementGuid>8b6cc021-2380-4514-87c1-cd488df3a0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>993e9b31-02bb-4114-8b42-cb56e3345405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>c058f38e-2038-48d5-99c3-6f3d0c1f10bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exULPolQuoteNum-1045-0' and @name = 'exULGLArray_0_exULPolQuoteNum']</value>
      <webElementGuid>c0ab0f9c-5ca3-423a-bb7f-1836ca700169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
