<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_exAddSubjectives_0_exAddS_4dd6ca</name>
   <tag></tag>
   <elementGuidId>2816cf52-9752-4503-9b4e-7d96216b9fe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exAddSubjective-1168-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exAddSubjective-1168-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a27c96ec-4059-4840-876c-00b86e358d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exAddSubjective-1168-0</value>
      <webElementGuid>ce502f7d-107b-4dcb-9f0c-a788b90d8ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exAddSubjectives_0_exAddSubjective</value>
      <webElementGuid>b0bf7793-f335-40af-980a-32fe03a8930f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Text</value>
      <webElementGuid>972c33a2-896d-4429-9a43-2846f5179ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exAddSubjective-1168-0</value>
      <webElementGuid>c62001c7-5948-46e1-bf9b-c68f267dc4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small is-full-width</value>
      <webElementGuid>22eb3b57-c3a3-4c30-b67e-202e9f5272b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exAddSubjective-1168-0&quot;)</value>
      <webElementGuid>9d491fa4-5a45-466f-8b49-13f5c343f42f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exAddSubjective-1168-0']</value>
      <webElementGuid>279c07e1-6153-483f-a3cd-00ba6192b0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[5]/div/div/div/div[6]/div[3]/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>335dde3e-d0c9-4f90-811a-4bec2d4ad791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>c1cc1e96-0895-4a4e-97bd-ea36fa4eba94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exAddSubjective-1168-0' and @name = 'exAddSubjectives_0_exAddSubjective' and @placeholder = 'Enter Text']</value>
      <webElementGuid>a1de1d11-6aeb-41fa-be3d-a76c0527e3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
