<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Name_exULGLArray_0_exCarrierName</name>
   <tag></tag>
   <elementGuidId>75ebcf04-c664-4e88-9564-f88e8f6ad154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exCarrierName-1104-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exCarrierName-1104-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e512bb4-b02b-4998-8c7f-4d20cb54dd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exCarrierName-1104-0</value>
      <webElementGuid>5c1b22e2-92db-4db5-b185-8d3b2263f0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exCarrierName</value>
      <webElementGuid>86412c95-f094-4448-bb42-ae598d50076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exCarrierName-1104-0</value>
      <webElementGuid>b2a884d4-efe9-4598-a631-171e69cf6c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>6779a5cc-5268-47e2-afae-d4639ff13414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exCarrierName-1104-0&quot;)</value>
      <webElementGuid>20952668-0e1c-4b9c-80ec-9a37f1a07061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exCarrierName-1104-0']</value>
      <webElementGuid>98d9bc57-9136-46cc-b780-796c80fc6680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>ce869d39-1a9e-4525-9fb7-9db14f9f4f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>34850f20-af48-4612-bcc2-1720d98b8bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exCarrierName-1104-0' and @name = 'exULGLArray_0_exCarrierName']</value>
      <webElementGuid>2e75bdc9-fed0-481f-975e-83fe374a2977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
