<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Units of Exposure_exULGLArray_0_exGLL_eb2adf</name>
   <tag></tag>
   <elementGuidId>7759ea17-51ad-407b-a932-507fedcdd70e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exUnitsOfExposure-1065-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exUnitsOfExposure-1065-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b85c7e0-1888-40e6-8082-0fb55a27a06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2795e5d0-9f7c-45b1-b1c7-4a7832ce8c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>acb17fc1-c4e6-4572-aaf9-4fa019c0c782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exUnitsOfExposure-1065-0</value>
      <webElementGuid>0fd8ef42-0639-4b02-85d8-cbeee7a9aeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exGLLocation_0_exUnitsOfExposure</value>
      <webElementGuid>6a6bce17-bb4d-46fe-9b0f-91ccad397180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>50f98bde-d95c-42d1-8219-e12e001ed2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exUnitsOfExposure-1065-0&quot;)</value>
      <webElementGuid>f63179ab-85bb-467e-ab4f-86d62fe7164f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exUnitsOfExposure-1065-0']</value>
      <webElementGuid>a9aed117-3cb4-4e4c-90ed-446be5ff5709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[10]/div[3]/div/div[2]/div[4]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>8a80c632-8420-42f2-9a1a-de7d65e0fcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>112c304b-382e-4f6b-902f-3eafa8ca8ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exUnitsOfExposure-1065-0' and @name = 'exULGLArray_0_exGLLocation_0_exUnitsOfExposure']</value>
      <webElementGuid>725cb9ae-e6ef-4cc3-a1a1-4c614d638461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
