<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_exULALArray_0_exALLocation_1_043bea</name>
   <tag></tag>
   <elementGuidId>a177195c-1181-4210-bcf2-211859a9faae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exALZip-1147-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exALZip-1147-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e6fa9de-e5bc-4395-bb28-1eef58e0da3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exALZip-1147-1</value>
      <webElementGuid>aef45741-9566-49e1-b75f-0cabf02150be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_1_exALZip</value>
      <webElementGuid>08612e68-a7fc-4b60-85e9-c1a4318184af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exALZip-1147-1</value>
      <webElementGuid>d03b0488-1f2d-427c-a614-5c67882b64be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>42c0a21a-f6f6-46ac-82e2-b95f2c325cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exALZip-1147-1&quot;)</value>
      <webElementGuid>e2aee98d-f168-4b0f-a5d0-debcc548be15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exALZip-1147-1']</value>
      <webElementGuid>fab255a7-e6b3-4795-be19-00e966602402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>dcc6c7e7-da5c-49ef-a831-e82b3faf8e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>bc50b7ee-b674-40ba-9206-8232d570adf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exALZip-1147-1' and @name = 'exULALArray_0_exALLocation_1_exALZip']</value>
      <webElementGuid>46101bbd-3683-4e5c-93b9-e21f576319d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
