<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_loc_1_locZip</name>
   <tag></tag>
   <elementGuidId>da9ea68a-041f-429a-8ca1-a9f2c0a8f530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-locZip-170-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-locZip-170-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20373615-d6cd-469a-bde2-7d885f3e79f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-locZip-170-1</value>
      <webElementGuid>0497488d-6177-4c91-98ff-61f5e2336faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loc_1_locZip</value>
      <webElementGuid>f9e92662-03df-4e04-ac37-a013671a8c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-locZip-170-1</value>
      <webElementGuid>428ab3d7-a884-4885-a81a-f592b1a395c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>9b2c270a-1df5-4f79-9fca-0ca76699bb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-locZip-170-1&quot;)</value>
      <webElementGuid>f2995025-3c05-40a5-8fd3-d90be1b281fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-locZip-170-1']</value>
      <webElementGuid>5fb4af8c-f63a-4081-83d2-c4f41c5386c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div[3]/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>2c4d1584-1d60-47c1-b47e-a54dd5aea304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>71f11e3f-f1a1-48bc-bb7e-9e9d7b2b5098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-locZip-170-1' and @name = 'loc_1_locZip']</value>
      <webElementGuid>aa6f3230-9fa8-4744-9ba7-255a213a312f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
