<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buildng_exULGLArray_0_exGLLocation_0__f5934c</name>
   <tag></tag>
   <elementGuidId>8d706c86-07c6-43ac-a236-ae8261727be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exBuildingNumber-1053-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exBuildingNumber-1053-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0843f4ed-318c-4291-a78e-217ed95fa7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exBuildingNumber-1053-0</value>
      <webElementGuid>a38cc416-124d-418d-b28c-e09033bb3235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exGLLocation_0_exBuildingNumber</value>
      <webElementGuid>2014b8a1-c8ca-4d0f-8e6b-9c32111b94cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exBuildingNumber-1053-0</value>
      <webElementGuid>44d177b2-8f64-4783-82d0-c8d6ec37443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>2852351b-4336-4cec-94bb-f0ea21236a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exBuildingNumber-1053-0&quot;)</value>
      <webElementGuid>a77546c0-66bb-4889-a3ee-829de083a454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exBuildingNumber-1053-0']</value>
      <webElementGuid>407bc82a-c557-4206-a3de-1c5d02ca8171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[10]/div[3]/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a559cca6-07d8-4aa5-9424-6c532dc443ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>7bfbf311-be79-4f33-908c-fb40fbaa8a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exBuildingNumber-1053-0' and @name = 'exULGLArray_0_exGLLocation_0_exBuildingNumber']</value>
      <webElementGuid>3b19b088-d7dc-40d8-903f-7e560be55456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
