<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_exULALArray_0_exALLocation_0_a1f244</name>
   <tag></tag>
   <elementGuidId>ccb63e87-f76b-43e1-84e7-ce9b31d53501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exALZip-1147-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exALZip-1147-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7e75a60-039b-4a68-9234-928e69cfd48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exALZip-1147-0</value>
      <webElementGuid>a7ede97f-b264-4df3-b294-306701eef11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_0_exALZip</value>
      <webElementGuid>060b1167-039b-4009-bdce-4edfea971428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exALZip-1147-0</value>
      <webElementGuid>d931d5e2-ec6d-4f06-8df0-7ee57d5c7986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>30035681-b849-43d6-a903-d81c918b660b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exALZip-1147-0&quot;)</value>
      <webElementGuid>be7078ed-0b67-497b-b33d-6df7cc7b7ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exALZip-1147-0']</value>
      <webElementGuid>4bee38cc-11c4-40f7-95b6-9dac772d594a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>d5eb1ec9-9867-4425-a4d8-1f1abf06b73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8158be1c-5d61-438e-a985-209e84228475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exALZip-1147-0' and @name = 'exULALArray_0_exALLocation_0_exALZip']</value>
      <webElementGuid>c89c68b1-53e1-4e12-8a7a-98e92456c48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
