<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_insuredZip</name>
   <tag></tag>
   <elementGuidId>f1f2ba89-4ae5-4981-afda-1ab9b59a9dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-insuredZip-234</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-insuredZip-234']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>604dcc2a-3c6c-4ae5-852d-43a5b5ee8da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-insuredZip-234</value>
      <webElementGuid>96e4bfe8-4c69-41e8-b6c9-66233c82e4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insuredZip</value>
      <webElementGuid>57def692-45a0-4156-95fb-a1c29fd1e074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-insuredZip-234</value>
      <webElementGuid>800bdaf0-23cb-4c3f-a250-b463147473bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>3559da8c-467c-4524-91fe-745cc12fcceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-insuredZip-234&quot;)</value>
      <webElementGuid>0e4cb8a6-fff3-4223-a846-dcf8a63f893c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-insuredZip-234']</value>
      <webElementGuid>232c7f26-0a7b-434c-9968-fe7768510f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>eb2fcd4d-7ae7-40f2-9169-25bd3a211bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>310a28c6-8f4c-4301-8ee2-e3581b086dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-insuredZip-234' and @name = 'insuredZip']</value>
      <webElementGuid>37e7fdf7-f1a4-4a57-a098-54467807c1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
