<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Underlying Auto Liability Premium_exU_3f0a17</name>
   <tag></tag>
   <elementGuidId>572f8b3b-dc68-4ef8-a15e-2de0157d5d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULALUnderlyingPremium2-1157-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULALUnderlyingPremium2-1157-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12dea5ae-d4e5-44b9-a1e1-6c04e72b6c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd528250-6c5a-417e-8855-dc3f3180d02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>9e8e40c4-2046-4951-ba33-f32d59160783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULALUnderlyingPremium2-1157-0</value>
      <webElementGuid>8dec2b5e-ae06-435d-bcb4-10f48d9ce4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exULALUnderlyingPremium2</value>
      <webElementGuid>6f178c89-e0a0-4fbe-85a9-6a5385c87693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>3c09e1ad-a8b3-4073-a694-a3cc06aac0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULALUnderlyingPremium2-1157-0&quot;)</value>
      <webElementGuid>ec8551be-5acd-4a5a-a225-7d4f0250b11b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULALUnderlyingPremium2-1157-0']</value>
      <webElementGuid>9a4504dc-3b14-4ff8-b793-008c16724969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[3]/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>7fada3b8-1fb0-4a66-86da-92bb169cb4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>76c31d31-4993-4e29-8990-a35a40555737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exULALUnderlyingPremium2-1157-0' and @name = 'exULALArray_0_exULALUnderlyingPremium2']</value>
      <webElementGuid>5ad0a6de-b700-42c8-89f6-ff413971f0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
