<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quote_exULEBLArray_0_exULEBLQuoteNum</name>
   <tag></tag>
   <elementGuidId>105b6a2e-09c5-4e61-a924-9f08189be5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULEBLQuoteNum-1230-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULEBLQuoteNum-1230-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc3ea4a0-fe58-4735-bb14-11abd726de0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULEBLQuoteNum-1230-0</value>
      <webElementGuid>5ec4c2ac-9c77-4eda-bd0b-17a26f1cae3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULEBLArray_0_exULEBLQuoteNum</value>
      <webElementGuid>6422fe14-c090-481c-a141-c40ba87e5453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exULEBLQuoteNum-1230-0</value>
      <webElementGuid>0dda99eb-bd5a-49a2-8143-e8ede52c902e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>777d2170-3a24-47c6-848b-1efe16e7eaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULEBLQuoteNum-1230-0&quot;)</value>
      <webElementGuid>29134d08-9769-4366-b4cb-e43990b05617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULEBLQuoteNum-1230-0']</value>
      <webElementGuid>9eb936c0-433e-4835-a0c1-7995810fde6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>cdc81779-4403-4001-980b-ee69299905c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>6e2a4c28-4f86-4461-8aed-1497f7044be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exULEBLQuoteNum-1230-0' and @name = 'exULEBLArray_0_exULEBLQuoteNum']</value>
      <webElementGuid>9b2414e4-26d2-49c5-b938-04764bb8cf32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
