<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_insuredStreet</name>
   <tag></tag>
   <elementGuidId>a8a782d7-0055-4faf-91e9-93faa6e16802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-insuredStreet-236</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-insuredStreet-236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>635b6c96-1a2b-4112-95a8-7cbe6da38768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-insuredStreet-236</value>
      <webElementGuid>a356eb48-3e1b-441e-87d1-5282d73b1ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insuredStreet</value>
      <webElementGuid>d05fff37-71db-4038-ac9e-48d9296dfcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-insuredStreet-236</value>
      <webElementGuid>a85fa6cc-9186-4597-a75f-f11f1c45cac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>9a140a69-b429-4e42-8249-1d0a04027647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-insuredStreet-236&quot;)</value>
      <webElementGuid>6256f12a-6933-441c-b963-e35c84069d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-insuredStreet-236']</value>
      <webElementGuid>3c96cfea-2d9d-4d76-85f1-633890f6e7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>f2b92c2c-d7e8-4fc1-ad86-a4c297afeedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>4686a689-f9ad-40d0-90ea-01a49f15eb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-insuredStreet-236' and @name = 'insuredStreet']</value>
      <webElementGuid>9189e0f4-6e26-4be5-aa3c-92b4c933aa2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
