<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_exULEBLArray_0_exULEBLEffDate</name>
   <tag></tag>
   <elementGuidId>a6d4391e-c150-4c0f-8ef4-0b9a81ef0238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULEBLEffDate-1232-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULEBLEffDate-1232-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64f465ec-1ea9-4235-b95d-8288b539fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0e0a960-6e48-4868-acfb-41340d1b2661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5118d4bd-b5fc-48c6-a863-a661bff8fe80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>d14ab70f-c113-46bc-81d5-695237f3a817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULEBLEffDate-1232-0</value>
      <webElementGuid>54360caa-aee4-4f2e-904e-7b81e54bb796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULEBLArray_0_exULEBLEffDate</value>
      <webElementGuid>d16f333f-d557-4679-a96a-f526329ef5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>6f6d0529-4b3b-483d-bde4-0b638fa9140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULEBLEffDate-1232-0&quot;)</value>
      <webElementGuid>a4f9f6bf-f02c-4bce-b88a-8a5b5d26d52f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULEBLEffDate-1232-0']</value>
      <webElementGuid>375dd282-7c9a-47ce-90f9-8e5c9f4e7591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>edc3958d-b362-44a2-a9cf-b226d6975c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>20791a14-96f2-4912-ac70-24cee8a7b934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULEBLEffDate-1232-0' and @name = 'exULEBLArray_0_exULEBLEffDate']</value>
      <webElementGuid>2483dcb1-4d49-46a2-af04-6f73067bf057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
