<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy_exULELArray_0_exULELPolNum</name>
   <tag></tag>
   <elementGuidId>1002e5a6-5f45-40c9-b106-2debc38dd355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULELPolNum-1240-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULELPolNum-1240-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>999f278a-e5f7-48dc-ab7e-ba21f81b94d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULELPolNum-1240-0</value>
      <webElementGuid>8f997d33-680e-4dbe-b0ef-9b0673fa9e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exULELPolNum</value>
      <webElementGuid>b51a9d00-15e1-462b-83b7-7189cda29b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exULELPolNum-1240-0</value>
      <webElementGuid>c3fb6b9c-f332-4e60-bd46-3881e3a43fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>226f7b88-d8ca-45d8-85f1-0066535d8b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULELPolNum-1240-0&quot;)</value>
      <webElementGuid>e718a77f-8d88-4ca0-bee8-0cadb5944efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULELPolNum-1240-0']</value>
      <webElementGuid>9c3d8022-0820-488f-8832-db4843227ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8c0570ae-b754-40c5-9868-e21a7212ad6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>20359e39-f9a0-43e5-be18-047b72165fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exULELPolNum-1240-0' and @name = 'exULELArray_0_exULELPolNum']</value>
      <webElementGuid>f8cea49b-4f99-4a3c-a3f4-74c90f480bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
