<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non-Owned Auto ( of employees)_exULAL_c03e03</name>
   <tag></tag>
   <elementGuidId>425d5ebb-1e2f-4144-b87a-c96060985a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exNoOfEmployees-1139-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exNoOfEmployees-1139-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9967f025-14a2-4a07-a91e-41e4bc84637b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3280aa9d-d008-47da-aa4e-560a70816bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3f5cfc5c-b612-4db7-9d8e-61a8fa733102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exNoOfEmployees-1139-0</value>
      <webElementGuid>19e6140a-4589-4012-ad30-533b333ebe38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exNoOfEmployees</value>
      <webElementGuid>bb1e91f9-d415-4b78-8a7b-060b7bdf4619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>df728f35-c46b-421b-b976-bbf6b0b506f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exNoOfEmployees-1139-0&quot;)</value>
      <webElementGuid>26eb2b2c-af1f-48ba-916a-19be4516c4e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exNoOfEmployees-1139-0']</value>
      <webElementGuid>0c934962-7fe8-4a0e-883d-c54050efa4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>338d52b4-965a-4356-b1b7-114f61389d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>9ffc086a-3068-47bf-ac62-b39c21570c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exNoOfEmployees-1139-0' and @name = 'exULALArray_0_exNoOfEmployees']</value>
      <webElementGuid>357c4ec2-14a7-48bf-ab30-d00a74530557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
