<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason_reason</name>
   <tag></tag>
   <elementGuidId>cbf7093c-b385-4882-859b-3fb6935a415a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-reason-1209</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-reason-1209']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30c1d139-322d-4825-be66-4d2c96624808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-reason-1209</value>
      <webElementGuid>512f68b4-2239-459e-9f67-0abeb1df6067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>127adcd2-e97a-480a-86b6-fcf57aae54c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-reason-1209</value>
      <webElementGuid>eaeef3a6-3acc-4775-a45a-5a4de36db9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>d1211915-dc60-4469-821d-42058ce8b899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-reason-1209&quot;)</value>
      <webElementGuid>e0fc8dde-6593-4fcc-96cf-ce38b69b4d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-reason-1209']</value>
      <webElementGuid>205679a0-7afc-4e47-b0f4-6785c9fb15ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[17]/div/div/div/div[2]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>4b1c1eaf-6218-46b0-aafa-37f8946dd2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>72cece04-cf0a-434f-9912-de037786aa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-reason-1209' and @name = 'reason']</value>
      <webElementGuid>04e13ece-096e-4eae-8dad-219a2f9943c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
