<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_exULEBLArray_0_exULEB_3e940c</name>
   <tag></tag>
   <elementGuidId>9c9a55fd-d745-4a29-93b6-75059bec69e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULEBLExpDate-1235-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULEBLExpDate-1235-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ade3aaf-8f8d-4601-8584-a03cd81df57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b8a26c7-2e16-4fbe-bd89-1ec810272387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c791cfe6-9737-4ecf-a755-4b65f5dd96dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>01a22502-4a08-4561-b862-09da68a0b3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULEBLExpDate-1235-0</value>
      <webElementGuid>967a707d-db16-44c8-948d-c4f7b22049e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULEBLArray_0_exULEBLExpDate</value>
      <webElementGuid>715d5521-455c-4c78-b97d-0f043116e94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>44b7501b-c0e4-4f4e-99a9-ebd329a78c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULEBLExpDate-1235-0&quot;)</value>
      <webElementGuid>e6d49365-47d3-4fb5-bd7d-c798a6623af8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULEBLExpDate-1235-0']</value>
      <webElementGuid>38f03bdc-e15b-4830-b362-bb36737f9f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[4]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>4c7da43f-aba4-4f66-90ba-9e4b18ab4cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[4]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>41bde432-18ec-44b6-9fc3-9344781a7ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULEBLExpDate-1235-0' and @name = 'exULEBLArray_0_exULEBLExpDate']</value>
      <webElementGuid>be485335-f295-4ae6-97bd-ee497acb3e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
