<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Description_businessDescription</name>
   <tag></tag>
   <elementGuidId>5b4a4871-b823-4b11-a7a3-19182f7c9ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-businessDescription-1188</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-businessDescription-1188']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d3bb82d-6d85-47a7-b85b-67b2838ceb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-businessDescription-1188</value>
      <webElementGuid>0e4cd84d-2db6-40fc-bdf1-1396b9e22d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessDescription</value>
      <webElementGuid>69a7e19b-3ac2-4007-a619-d93dfaf80b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-businessDescription-1188</value>
      <webElementGuid>b8d58ebc-863d-4aad-bae6-5caff2bd08a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small is-full-width</value>
      <webElementGuid>387248db-9bd1-4ffb-b52c-88404af77e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-businessDescription-1188&quot;)</value>
      <webElementGuid>e376d59d-90ed-46fc-88f5-71a3faa42f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-businessDescription-1188']</value>
      <webElementGuid>ac7fc5ad-fbdd-4b9b-a5ee-d7c40f2bdc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[10]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a8f8c91a-f26c-49b1-ae65-d1687bf9773d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>aab4225d-41a8-4c80-8457-a4f1e5dc6cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-businessDescription-1188' and @name = 'businessDescription']</value>
      <webElementGuid>7122a4c4-46ff-4762-b7f0-bf801f3e88ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
