<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UGLX 5107_UGLX 5112</name>
   <tag></tag>
   <elementGuidId>3ce605f2-a9f4-447c-a2f1-ef142f955693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;UGLX 5112&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='UGLX 5112']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f531954-8fdc-40cd-8819-1bf90c28bfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>66c6ba30-75b2-4996-9e85-c65d3688f6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4d31f2ba-01dd-4de4-b553-1d7b900d6a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UGLX 5112</value>
      <webElementGuid>edf3b9ef-9992-46f0-b1ee-a045ee60fdae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>true-value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>223a70d9-6851-43ad-be5e-a8746ead20b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UGLX 5112</value>
      <webElementGuid>21cb069b-7ba4-4d0c-86b4-7243fe159c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forms-table&quot;)/tbody[2]/tr[15]/td[1]/label[@class=&quot;checkbox small&quot;]/input[1]</value>
      <webElementGuid>d4ace379-4cfd-47b8-8fdc-5b1a87e448e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='UGLX 5112']</value>
      <webElementGuid>34594fa7-6391-4413-a331-99a1393316ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='forms-table']/tbody[2]/tr[15]/td/label/input</value>
      <webElementGuid>cf498487-9b27-4a36-948b-6585be937e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/label/input</value>
      <webElementGuid>a1222ef5-b388-41be-9350-a621594393cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'UGLX 5112']</value>
      <webElementGuid>cf6b3661-54ad-445d-85ad-8a9308514b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
