<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hired Auto Cost per Hire_exULALArray__48a351</name>
   <tag></tag>
   <elementGuidId>b6af8d9c-1b2c-4e0b-bff2-74d58c126005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exHiredCostperHire-1138-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exHiredCostperHire-1138-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>997d8810-5825-40a5-88a4-295cb12bd3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>965b845e-79f0-400f-8043-7eef95c42587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1c33beaf-ece0-46b0-9014-c8c433d4d03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exHiredCostperHire-1138-0</value>
      <webElementGuid>9ded5c33-0316-469b-9ac0-a179f6ba3758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exHiredCostperHire</value>
      <webElementGuid>41f22090-79b3-4473-a6e0-be9f68239d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>603fb148-9683-4d5e-87a7-69c5cedeef2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exHiredCostperHire-1138-0&quot;)</value>
      <webElementGuid>5631a7ea-0212-43f8-b7aa-38dce5ff5675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exHiredCostperHire-1138-0']</value>
      <webElementGuid>dc3e38b5-cc4f-4083-a9b7-832cd2f4984e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>f7271cf2-3d42-41a7-8284-f428eb0e3bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>2f44dbe8-52b3-45c6-9e0d-6035134b7c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exHiredCostperHire-1138-0' and @name = 'exULALArray_0_exHiredCostperHire']</value>
      <webElementGuid>fb221c09-3335-4413-9754-d7edc3d37bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
