<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Name_exULALArray_0_exALCarrier</name>
   <tag></tag>
   <elementGuidId>6067304a-75c3-4e13-bc2d-c97377d6cd7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exALCarrier-1153-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exALCarrier-1153-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f030477-3947-4944-8725-1339364c21ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exALCarrier-1153-0</value>
      <webElementGuid>826d7533-d46c-4a9f-af5b-e874df485869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALCarrier</value>
      <webElementGuid>3aeb4083-929d-4c6b-bfaa-41fc408cb41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-exALCarrier-1153-0</value>
      <webElementGuid>69a334db-6c9b-496c-b109-56edb50346d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>96fbd05e-19e9-441b-bf00-555282f30157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exALCarrier-1153-0&quot;)</value>
      <webElementGuid>b4cbf7e4-9337-402e-91b9-bb999ca03b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exALCarrier-1153-0']</value>
      <webElementGuid>2f764f25-9581-4511-8b31-f23572cc6f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>2b0f0ab1-6931-4d19-8d48-6e9738fae3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>7226536f-cab0-4897-9e7d-e66221c5675e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-exALCarrier-1153-0' and @name = 'exULALArray_0_exALCarrier']</value>
      <webElementGuid>7947b22e-7d2e-464a-973a-645d1b31a9b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
