<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_exULELArray_0_exULELExpDate</name>
   <tag></tag>
   <elementGuidId>98d96757-de8f-4039-bbcd-a7b5df34c6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULELExpDate-1242-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULELExpDate-1242-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f268309-072e-480e-949d-c1fa16da6d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3daf3cd5-506f-4b3f-9c4a-3fcbf392b74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f79e8134-c597-445e-b458-c180ae020123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>09f441da-98ff-4412-a2df-27748751fe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULELExpDate-1242-0</value>
      <webElementGuid>a0b45806-3954-46cb-8182-37f97636fd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exULELExpDate</value>
      <webElementGuid>bc0957bf-e430-4722-a2c6-b5965ccd5765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>401dc638-c846-46c5-a65b-a963f4a329d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULELExpDate-1242-0&quot;)</value>
      <webElementGuid>35fa7795-71b1-4387-9a4e-175601af93c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULELExpDate-1242-0']</value>
      <webElementGuid>73758995-bf96-4992-a7bb-5d6cba18e845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[4]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d70f00ba-189a-4fa4-b822-19f3b9c01537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[4]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>c621c0df-ea61-4cf6-8e05-1f92a9570ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULELExpDate-1242-0' and @name = 'exULELArray_0_exULELExpDate']</value>
      <webElementGuid>ea332714-f5a7-4de9-942f-d1029e43aa4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
