<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IRPM_excessIRPM</name>
   <tag></tag>
   <elementGuidId>6ed997b5-cae9-42e5-bafc-2c1f893f6438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-excessIRPM-1282</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-excessIRPM-1282']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>811a04ad-c9c9-47eb-9c8e-edde8e3262d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcd65bb3-a4d2-4a16-b34e-a34762570bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>abf6debd-163e-4e74-89f2-1a76b1de78e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-excessIRPM-1282</value>
      <webElementGuid>0a4131d7-7a7b-4473-aa9a-93ade1918c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>excessIRPM</value>
      <webElementGuid>c0de33dc-373f-4075-bd24-d36a37a4fb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>274fccbf-3f93-4a9d-8497-cef4f1ab1c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-excessIRPM-1282&quot;)</value>
      <webElementGuid>16b4cf38-bb47-4334-a6e9-1ecc8b6f2476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-excessIRPM-1282']</value>
      <webElementGuid>2a7bb836-454f-453d-b14b-0eefae513f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div[5]/div/div/div/div[4]/div/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>b45ff7f4-90b5-4e0b-b03d-3740cd9db2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>4f7c67e3-66b9-4934-8405-a0d0cf0eede7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-excessIRPM-1282' and @name = 'excessIRPM']</value>
      <webElementGuid>940a227c-f32f-46b7-8281-f39524aff432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
