<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vehicles_exULALArray_0_exALLocation_1_83d279</name>
   <tag></tag>
   <elementGuidId>32d4b330-baf3-45c2-a7f1-d51deb3fbcda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exALExposure-1150-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exALExposure-1150-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03edf491-934a-418d-b7c0-41a5795c24a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84f119f0-751f-43c9-a5da-c76f86e7e0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a52cce88-641b-451c-8362-c2c5907e8c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exALExposure-1150-1</value>
      <webElementGuid>f895d9e5-d1bd-449a-a5d3-21b166e80fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_1_exALExposure</value>
      <webElementGuid>7ccb6e0c-3060-405e-b550-450fb27e0873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>22156874-4c18-43f6-bfe6-44a77b70a9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>20eb1cdc-b8d8-4d0a-b1a7-30dee14d1db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exALExposure-1150-1&quot;)</value>
      <webElementGuid>f1be07f0-23f4-4141-a711-0a95ceaa68ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exALExposure-1150-1']</value>
      <webElementGuid>531e3e8f-f2de-4f8e-a06c-6ffd7210f999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div[2]/div/div/div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>17c56a64-5685-4244-aeed-2ca507be9be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[9]/div/div/div[2]/div/input</value>
      <webElementGuid>ea50f554-5ea5-40f5-9588-c241a9299425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exALExposure-1150-1' and @name = 'exULALArray_0_exALLocation_1_exALExposure' and @placeholder = '#']</value>
      <webElementGuid>0761019d-ef31-412a-a9e7-b3ed6203af91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
