<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Class Code_exULGLArray_0_exGLLocation_a36977</name>
   <tag></tag>
   <elementGuidId>aa9fa445-f779-4771-acc9-be6199c6f69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exClassCode-1059-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exClassCode-1059-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3b44e11-c039-45cb-ba29-d69d02ed83f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f361d571-358e-4ac9-868f-1fe54a389acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>604656fd-e929-4ac0-8afe-f2332a1d205d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>'list'</value>
      <webElementGuid>08ab524f-eba8-44c3-b051-934d8cb26387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>autocomplete-input</value>
      <webElementGuid>a80474fb-1903-4f0d-89b3-51ca6995cd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exClassCode-1059-0</value>
      <webElementGuid>7ac46133-a2f6-4d93-96c9-60e7e2f01ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exGLLocation_0_exClassCode</value>
      <webElementGuid>df319b56-db6d-4dd9-aea8-49ea8d3ca94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small is-full-width</value>
      <webElementGuid>45e94a3d-2d2e-4b97-b793-10541bdab647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exClassCode-1059-0&quot;)</value>
      <webElementGuid>fcae619d-5eff-439d-93c7-d6ae9df6b782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exClassCode-1059-0']</value>
      <webElementGuid>c2706df2-e472-4d74-90ed-51c161cb986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[10]/div[3]/div/div[2]/div[3]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>bfec4b01-6ec4-4286-b02e-8fd28ee50f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>d2d31031-f257-4d08-b7eb-eb0fd222ae7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exClassCode-1059-0' and @name = 'exULGLArray_0_exGLLocation_0_exClassCode']</value>
      <webElementGuid>4284a44b-aba2-4b6f-90f6-7f39531c97b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
