<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_loc_0_locZip</name>
   <tag></tag>
   <elementGuidId>cc13795b-10f6-49bb-a07f-e50182460428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-locZip-170-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-locZip-170-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9d5186e-b3e6-480c-a6cd-f2d3ab54e2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-locZip-170-0</value>
      <webElementGuid>bd8878f7-4288-4a3a-b8c1-fc88e7bed2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loc_0_locZip</value>
      <webElementGuid>dc39e5b3-7f7e-46da-9bfb-3d312207e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-locZip-170-0</value>
      <webElementGuid>6496d7e9-33ae-4ed8-b895-626d6de17039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>52023d27-c992-45eb-b43d-e788864740ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-locZip-170-0&quot;)</value>
      <webElementGuid>34b60ead-377d-4371-98c1-0562b7440fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-locZip-170-0']</value>
      <webElementGuid>b82f144f-8372-45c5-95c1-e6878d23ffa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div[3]/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>e3a0e45b-8555-47e8-8df9-45e3b9eeb91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>af708d5f-e906-47dc-89fe-a9fe13e14960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-locZip-170-0' and @name = 'loc_0_locZip']</value>
      <webElementGuid>e0f694cd-a609-4e87-a846-c041647f4360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
