<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_dateSummary</name>
   <tag></tag>
   <elementGuidId>1a2f4cc9-7f12-498a-b8af-2f81d8104c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-dateSummary-1306</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-dateSummary-1306']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>facb386b-933a-450e-bcff-fe2c9a522c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a853eb44-6b4a-4e46-a97b-d861bdc44846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1b0bde3-2004-4ab0-bebb-ea9533e7d59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>dc32e92a-81fa-4484-a08f-77e431042c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-dateSummary-1306</value>
      <webElementGuid>4dbf03e9-35fb-4472-88ae-d3a5a9fffe4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateSummary</value>
      <webElementGuid>6c07986c-ac06-44ab-be78-49358082dedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>1a60a12e-c5ab-4d52-b021-dcc4f39313d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-dateSummary-1306&quot;)</value>
      <webElementGuid>6e962f1b-589d-4675-a631-689976c651d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-dateSummary-1306']</value>
      <webElementGuid>158b57ce-578e-4ecf-b6ae-dab850adb439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[20]/div/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7569e21e-a0e6-4691-9fb2-ab55809235d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[5]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>021fb4b3-83aa-49d7-929c-84acb92d81af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-dateSummary-1306' and @name = 'dateSummary']</value>
      <webElementGuid>b0c68425-efc1-4591-bcf7-a24f10308d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
