<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_loc_0_locStreet</name>
   <tag></tag>
   <elementGuidId>f7b4cad0-0494-4762-882e-202091373152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-locStreet-172-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-locStreet-172-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09b04168-efe2-49c8-9f7f-5d3e0a126485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-locStreet-172-0</value>
      <webElementGuid>f0db4a56-ecfc-4e72-96a7-567911668c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loc_0_locStreet</value>
      <webElementGuid>45f89dd9-f68e-4718-a086-f21bb78f36c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-locStreet-172-0</value>
      <webElementGuid>602841c8-f260-41e3-9fa2-16fd63e3ce78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>d600d453-4223-49ca-96c5-08c8ca7a090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-locStreet-172-0&quot;)</value>
      <webElementGuid>993ad91c-2570-4956-b271-5af9f4c07d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-locStreet-172-0']</value>
      <webElementGuid>1dd443f3-e064-48e1-a2e9-3d93d96d2f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div[3]/div/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>94905911-eccb-4654-9315-17cdb875c7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>9d82f2f2-4236-4899-989e-d04401f77ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-locStreet-172-0' and @name = 'loc_0_locStreet']</value>
      <webElementGuid>182d22be-a295-41fe-8c95-ca06866fc36c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
