<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Scheduled Autos and Hired  Non-_0c781e</name>
   <tag></tag>
   <elementGuidId>b3439838-c974-406b-b893-315ab5bf122f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exHiredPrem-1140-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exHiredPrem-1140-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06340442-c0f4-43ef-8d13-6039ae5ba518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68e96a19-4680-4d79-b60e-60358079e2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8a884ede-75de-4f8e-9a73-d6d42181bc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exHiredPrem-1140-0</value>
      <webElementGuid>0b9b7dbc-a377-479b-8319-e0762d677b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exHiredPrem</value>
      <webElementGuid>fec100fb-9540-461b-9b57-ec821d8597be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>0340f331-85be-4faf-a05f-db53180bb404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exHiredPrem-1140-0&quot;)</value>
      <webElementGuid>cea5d503-01b8-47bd-b0cc-78c328eb7811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exHiredPrem-1140-0']</value>
      <webElementGuid>576654f1-007e-4b41-b1da-346ef1844da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div/div/div[4]/div/div/div[2]/div/input</value>
      <webElementGuid>44a48c64-069f-407e-9036-0fcf9899ecf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[4]/div/div/div[2]/div/input</value>
      <webElementGuid>7aaed62d-c457-4593-a04b-523a079990fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-exHiredPrem-1140-0' and @name = 'exULALArray_0_exHiredPrem']</value>
      <webElementGuid>4d561101-95ce-4a28-bbea-41803c8e159b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
