<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of years in Business_numberOfY_b1d71d</name>
   <tag></tag>
   <elementGuidId>1901c711-8648-4b0f-9c39-b80ff363a716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-numberOfYearsInBusiness-1197</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-numberOfYearsInBusiness-1197']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e54b2f73-b609-4413-92d4-36a7798f03ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>240a6bb1-8d94-43e2-84c4-227ba67c7b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c53848e9-a4ee-4378-8afd-010a74ad321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-numberOfYearsInBusiness-1197</value>
      <webElementGuid>21fc56b8-a3f5-47c9-9930-b11442daedf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfYearsInBusiness</value>
      <webElementGuid>ba815976-9676-4b78-8d8c-eabee6d64bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>fd05ad41-7b67-4a22-ae18-91120cc05524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-numberOfYearsInBusiness-1197&quot;)</value>
      <webElementGuid>420f2386-e71c-4ed0-843b-ce4bc455e6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-numberOfYearsInBusiness-1197']</value>
      <webElementGuid>d1385fc3-3850-4a16-977a-940eee75e975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[14]/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>a07f81ba-f593-4011-bac9-ed1a2d7cd8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>74f5dfc1-30f8-4526-86ff-b6b745b582be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'field-numberOfYearsInBusiness-1197' and @name = 'numberOfYearsInBusiness']</value>
      <webElementGuid>62b7ac60-4170-4fa1-ab13-ec1805f9262c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
