<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_exULALArray_0_exULALExpDate</name>
   <tag></tag>
   <elementGuidId>b1ccb5f8-d516-4e21-a37b-3a9fe4a9565b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULALExpDate-1156-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-exULALExpDate-1156-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c54cb0c-81f4-4ee4-aa32-1115b21ab65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98186747-e60e-4221-937c-536dff2be9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6514d014-50ef-4861-be24-b3eb89f7d525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>220c070b-4bbc-48ab-a312-fd2cd8aa0f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULALExpDate-1156-0</value>
      <webElementGuid>9fb5d176-a1ad-4d74-b34b-8411d3b5b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exULALExpDate</value>
      <webElementGuid>bd18f1a2-eff5-4d35-9e1b-48857b6f05db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small</value>
      <webElementGuid>212ca63d-17c9-43d0-9b0d-849f9e27d530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULALExpDate-1156-0&quot;)</value>
      <webElementGuid>5ee0daf2-27e8-481c-af63-7d39fbcd6f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-exULALExpDate-1156-0']</value>
      <webElementGuid>0b82b8dc-1fcd-4264-9f27-bd5b15e6d698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ec6ccb29-a2be-4c64-85ce-f35e173d42ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>951858e2-4ea3-42fd-b7b8-a480c29bf094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pick a date' and @id = 'field-exULALExpDate-1156-0' and @name = 'exULALArray_0_exULALExpDate']</value>
      <webElementGuid>d5acfe95-ba31-421b-95e4-22eba82a861c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
