<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1,000,000  2,000,000_1_2</name>
   <tag></tag>
   <elementGuidId>591739dd-ed94-445b-849e-0c25efaee9dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULELBIEachAccLimit-1243-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exULELBIEachAccLimit-1243-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>741b5492-395b-4f09-a546-18ae5b9341b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULELArray_0_exULELBIEachAccLimit</value>
      <webElementGuid>309844b1-378d-4121-a249-ec91d6a1cf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULELArray_0_exULELBIEachAccLimit</value>
      <webElementGuid>13ba3991-8cd5-4590-b1c0-d643535a30e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULELBIEachAccLimit-1243-0</value>
      <webElementGuid>c102ef56-42d1-4ab1-9cc5-ca7758a1f413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $1,000,000  $2,000,000 </value>
      <webElementGuid>c4fe0046-60e2-4a61-82cf-22f7d8286b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULELBIEachAccLimit-1243-0&quot;)</value>
      <webElementGuid>a4339bcb-ff0b-4d92-9e11-e232df910bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exULELBIEachAccLimit-1243-0']</value>
      <webElementGuid>2397c89f-7429-4ec1-a4e3-4150d95aae01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[6]/div/div/div/div/div[3]/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>89541164-999d-44c4-8739-f14a670535a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bodily Injury Each Accident'])[1]/following::select[1]</value>
      <webElementGuid>b959e8a1-5688-46ca-a4c1-79abf2010e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers Liability Limits:'])[1]/following::select[1]</value>
      <webElementGuid>7050a7d6-dc1e-479c-be3a-537a8fa458c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bodily Injury by Disease Policy Limit'])[1]/preceding::select[1]</value>
      <webElementGuid>5b8949a0-c210-4555-8033-30692ee23957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div[3]/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>5b7fc3e2-7d35-436e-a666-12e5e22591e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULELArray_0_exULELBIEachAccLimit' and @id = 'field-exULELBIEachAccLimit-1243-0' and (text() = ' $1,000,000  $2,000,000 ' or . = ' $1,000,000  $2,000,000 ')]</value>
      <webElementGuid>91cddeb9-7985-42c4-80d4-64f0628dda3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
