<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1,000,000  2,000,000  3,000,000  4,0_52d254</name>
   <tag></tag>
   <elementGuidId>3a1621d8-58d4-4bb1-a19a-3e65f96bd6e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULGLPersonalAdvInjury-1050-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exULGLPersonalAdvInjury-1050-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1e9b6133-3c54-4343-8c90-88a04c08f44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULGLArray_0_exULGLPersonalAdvInjury</value>
      <webElementGuid>9cda742d-f3b8-4b03-bde4-ccb1787f8419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exULGLPersonalAdvInjury</value>
      <webElementGuid>281dea3f-b421-4f8f-a283-827c169c75cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULGLPersonalAdvInjury-1050-0</value>
      <webElementGuid>56adbdf0-72c8-4aa6-a108-6767eb4b15fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000  Included  Excluded  N/A </value>
      <webElementGuid>5d736569-a45a-460b-979e-506c2a812e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULGLPersonalAdvInjury-1050-0&quot;)</value>
      <webElementGuid>7559f59d-ac36-4186-b223-56eae3deb90d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exULGLPersonalAdvInjury-1050-0']</value>
      <webElementGuid>37ee1ab1-18ce-4a2a-bbf0-52ab46339b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div[4]/div/div/div[2]/div/span/select</value>
      <webElementGuid>f7ed543a-3688-4471-887c-11a66b969970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal &amp; Advertising Injury'])[1]/following::select[1]</value>
      <webElementGuid>39833d0d-8e7b-4410-ab34-41958b294807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible*'])[1]/preceding::select[1]</value>
      <webElementGuid>56097dd8-b391-46c3-b28e-bc52471ba550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/span/select</value>
      <webElementGuid>eead7693-a7a1-43c0-ad92-97900f59547d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULGLArray_0_exULGLPersonalAdvInjury' and @id = 'field-exULGLPersonalAdvInjury-1050-0' and (text() = ' $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000  Included  Excluded  N/A ' or . = ' $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000  Included  Excluded  N/A ')]</value>
      <webElementGuid>6688e99b-0ba8-4b2f-a876-34c0be65475a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
