<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Private Passenger Types Cl_db109a</name>
   <tag></tag>
   <elementGuidId>fc2a8145-1631-4cb9-9aea-c20a31b47bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exAutoSizeClass-1145-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exAutoSizeClass-1145-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e57ec87b-3774-425b-9863-76d99b521bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULALArray_0_exALLocation_0_exAutoSizeClass</value>
      <webElementGuid>a69e9bfb-9f2c-48fe-922f-22f687046cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_0_exAutoSizeClass</value>
      <webElementGuid>901962be-8b20-49b5-9c81-873829fddafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exAutoSizeClass-1145-0</value>
      <webElementGuid>ea0617a7-eaa9-4617-8dd8-6cbda02924ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) </value>
      <webElementGuid>0000252e-16cc-4ef0-b0d0-09ee8675a379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exAutoSizeClass-1145-0&quot;)</value>
      <webElementGuid>02e3aefb-1ca2-468f-8eb6-15ec8335a573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exAutoSizeClass-1145-0']</value>
      <webElementGuid>4ff1c3f9-7a7b-4b26-985a-9efcede481b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div/div[2]/div/div/div[5]/div/div/div[2]/div/span/select</value>
      <webElementGuid>e8cd3d29-eac9-44d6-829c-5f65a75a57d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Size Class*'])[1]/following::select[1]</value>
      <webElementGuid>067b0980-bb99-460d-ac42-ddf43d5063d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Territory Code'])[2]/following::select[1]</value>
      <webElementGuid>f8ba19b8-f599-4cda-b1be-1c75e7021447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Business Use Class*'])[1]/preceding::select[1]</value>
      <webElementGuid>25047fa0-2201-45f0-bc9c-bdd865ba19d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/span/select</value>
      <webElementGuid>cfb0b1f0-46b4-4116-83f5-57012a7ef122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULALArray_0_exALLocation_0_exAutoSizeClass' and @id = 'field-exAutoSizeClass-1145-0' and (text() = ' (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) ' or . = ' (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) ')]</value>
      <webElementGuid>3e85fb87-0d09-419b-b56f-c09bcada80e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
