<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Private Passenger Types Cl_db109a_1</name>
   <tag></tag>
   <elementGuidId>cd84214a-7f7a-4a43-b1c1-48a1e6adc51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exAutoSizeClass-1145-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exAutoSizeClass-1145-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18cef32c-e67d-4f8b-b459-577ae750e6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULALArray_0_exALLocation_1_exAutoSizeClass</value>
      <webElementGuid>71330d64-8712-487a-afc9-a968428cd81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_1_exAutoSizeClass</value>
      <webElementGuid>e0f6be0e-dd4c-407b-a0d2-e3e2864a93d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exAutoSizeClass-1145-1</value>
      <webElementGuid>e84b1a0b-c40b-40e2-be80-93eec4df7ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) </value>
      <webElementGuid>2b0f3869-2a3e-45ce-8952-07d85938ab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exAutoSizeClass-1145-1&quot;)</value>
      <webElementGuid>184b2f3b-7d85-4059-866f-23a77511602f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exAutoSizeClass-1145-1']</value>
      <webElementGuid>fdd3dea0-efaf-486c-b961-322d609def81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div[2]/div/div/div[5]/div/div/div[2]/div/span/select</value>
      <webElementGuid>ced75407-1f78-4407-8372-af1e77c3d9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Size Class*'])[1]/following::select[1]</value>
      <webElementGuid>a76ddbd5-cd05-4f59-847d-b7ee56a932f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Territory Code'])[2]/following::select[1]</value>
      <webElementGuid>24258318-71a7-4df5-968d-4ff4973f6d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Business Use Class*'])[1]/preceding::select[1]</value>
      <webElementGuid>7c37f166-e86e-461c-bbf6-2d670ac19f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/span/select</value>
      <webElementGuid>9888068b-d349-4fa5-84cc-21fed8b61425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULALArray_0_exALLocation_1_exAutoSizeClass' and @id = 'field-exAutoSizeClass-1145-1' and (text() = ' (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) ' or . = ' (Select)  Private Passenger Types Classifications  Light Trucks (0 - 10,000 lbs. GVWR)  Medium Trucks (10,001 - 20,000 lbs. GVWR)  Heavy Trucks (20,001 - 45,000 lbs. GVWR)  Heavy Truck-tractors (0 - 45,000 lbs. GCW)  Extra-heavy Truck-tractors (Over 45,000 lbs. GCW) ')]</value>
      <webElementGuid>514b3296-48ff-4dc3-a176-44f0a77045e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
