<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Primary  Excess</name>
   <tag></tag>
   <elementGuidId>36d2e6e6-fcdf-4422-926e-e1e8d519a905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exPrimaryExcess-1040</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exPrimaryExcess-1040']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11a4c281-0098-4da5-b20a-9a0e9cefa750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exPrimaryExcess</value>
      <webElementGuid>f64835e9-9bfb-41e7-8a93-5cc7a017a414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exPrimaryExcess</value>
      <webElementGuid>f664a7d2-2025-461f-b7e5-0d6b2de3d392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exPrimaryExcess-1040</value>
      <webElementGuid>fd5d7700-505d-46ce-b0ae-0458ac2049f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Primary  Excess </value>
      <webElementGuid>f741ce01-da9f-42e8-8a2e-48d7906753fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exPrimaryExcess-1040&quot;)</value>
      <webElementGuid>a29226c6-614d-4209-a90b-cd8ba76d6a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exPrimaryExcess-1040']</value>
      <webElementGuid>824ad175-32fa-4539-8f67-557c4fb23221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[3]/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>0382abf0-8bf7-47ac-aa7d-6ea08e64b503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary or Excess?*'])[1]/following::select[1]</value>
      <webElementGuid>6ad09226-3c3b-45a8-8124-578decb4dea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underlying GL Limit*'])[1]/preceding::select[1]</value>
      <webElementGuid>02a08b90-1aa3-44d7-b331-1ac4b6ce6c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>18daa3a9-23c2-4eec-9df9-0a5c1e30e48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exPrimaryExcess' and @id = 'field-exPrimaryExcess-1040' and (text() = ' Primary  Excess ' or . = ' Primary  Excess ')]</value>
      <webElementGuid>9d1566d2-1ec2-439b-b77c-21ee5cb7cda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
