<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Yes  No</name>
   <tag></tag>
   <elementGuidId>a4c9f455-a8a7-474b-b183-8561a29da824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-supplemental-1205</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-supplemental-1205']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c7ef6e54-105d-4926-af3c-36b51d102777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-supplemental</value>
      <webElementGuid>aaaa41d0-7a21-437d-8bf1-091a056b0ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplemental</value>
      <webElementGuid>4428b9d3-89e7-49eb-9e92-cb0170a1c96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-supplemental-1205</value>
      <webElementGuid>fb7c923c-1c51-47f2-b57e-cd8ed5a0e377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes  No </value>
      <webElementGuid>26d03133-9c02-4d16-ac11-b1316a68bf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-supplemental-1205&quot;)</value>
      <webElementGuid>bd4c6be2-9715-4ea7-861c-514189368afd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-supplemental-1205']</value>
      <webElementGuid>956a55da-79c6-44d8-8649-217aa1780713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[17]/div/div/div/div/div/div[2]/div/div/div[2]/div/span/select</value>
      <webElementGuid>efeb0d2d-f012-4317-abc9-c68266c48768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Experience:'])[1]/following::select[1]</value>
      <webElementGuid>431a94a2-c196-4c69-8f48-aef0dfcdd408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason:'])[1]/preceding::select[1]</value>
      <webElementGuid>9051f63f-ea9b-4fe9-8f37-9f4b86c805d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/select</value>
      <webElementGuid>97e55d45-5235-46d4-be5b-83099a82d813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'supplemental' and @id = 'field-supplemental-1205' and (text() = ' Yes  No ' or . = ' Yes  No ')]</value>
      <webElementGuid>cea8cd4c-072b-4d24-85cc-347694c071a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
