<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  3,000,000  Included  Excluded</name>
   <tag></tag>
   <elementGuidId>87ef662a-b7d0-4750-a862-4afc21c93186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULGLProductsCompletedOps-1049-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exULGLProductsCompletedOps-1049-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdec137f-c940-4ba2-a8f0-b3055320a5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULGLArray_0_exULGLProductsCompletedOps</value>
      <webElementGuid>27e55133-c9cc-4dc6-a784-59c5b5e9d323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exULGLProductsCompletedOps</value>
      <webElementGuid>828e0dbc-50b3-44c8-9786-c6f98023962e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULGLProductsCompletedOps-1049-0</value>
      <webElementGuid>b1753d99-7de0-4440-a3aa-1fe51c21e4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  $3,000,000  Included  Excluded </value>
      <webElementGuid>371d1db1-d26b-4363-9730-96c4a529a93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULGLProductsCompletedOps-1049-0&quot;)</value>
      <webElementGuid>43dcc61f-19d9-49cc-bbdc-c7c69fbd38c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exULGLProductsCompletedOps-1049-0']</value>
      <webElementGuid>8a476053-27a6-44af-b062-0991b1a6a169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div[3]/div/div/div[2]/div/span/select</value>
      <webElementGuid>4687eb1f-55a4-42bf-85bd-9d6f19682891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products-Completed Operations Aggregate Limit*'])[1]/following::select[1]</value>
      <webElementGuid>2e96cb2c-301f-468a-96d4-09573b474893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal &amp; Advertising Injury'])[1]/preceding::select[1]</value>
      <webElementGuid>6a375bcd-d79b-46cc-b9f9-d664b2ff68c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/div[2]/div/span/select</value>
      <webElementGuid>2dffaafa-9f60-464e-a04e-016120156680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULGLArray_0_exULGLProductsCompletedOps' and @id = 'field-exULGLProductsCompletedOps-1049-0' and (text() = ' (select)  $3,000,000  Included  Excluded ' or . = ' (select)  $3,000,000  Included  Excluded ')]</value>
      <webElementGuid>9a4e9eab-640b-437b-acc7-bbf6a4028431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
