<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1,000,000  2,000,000  3,000,000  4,0_8e714a</name>
   <tag></tag>
   <elementGuidId>19057ead-a279-4aef-aae4-b6cab6886ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exEachOccurrencePL-1032</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exEachOccurrencePL-1032']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2dd0a06d-a666-4a31-87e3-e4624949be8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exEachOccurrencePL</value>
      <webElementGuid>dda966f5-4864-47f4-a42e-4b718b375c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exEachOccurrencePL</value>
      <webElementGuid>4ca65af3-a1b2-45bb-b2ff-40fb67041d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exEachOccurrencePL-1032</value>
      <webElementGuid>e1b554e1-13f7-4905-b92d-75473635be53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000 </value>
      <webElementGuid>75955960-b7e1-42d5-96b0-f41215170118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exEachOccurrencePL-1032&quot;)</value>
      <webElementGuid>80b3b3c7-98ff-4379-85b8-39cd5796ebc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exEachOccurrencePL-1032']</value>
      <webElementGuid>0df81c9d-c66a-4a17-8924-a7ca892634b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>8056fdf3-719b-47f3-9018-cd8bccded8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Each Occurrence Limit'])[1]/following::select[1]</value>
      <webElementGuid>0797d03f-daac-43a5-ab6c-baa0fbf88cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excess Policy Limits:'])[1]/following::select[1]</value>
      <webElementGuid>e652a7e5-dcd5-4b3d-b449-20625c59c5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregate Limit'])[1]/preceding::select[1]</value>
      <webElementGuid>75b87db0-7a2f-484f-9d36-01699c2c88f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>9810c6ab-dd54-4bd6-b4fe-d630d7c2dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exEachOccurrencePL' and @id = 'field-exEachOccurrencePL-1032' and (text() = ' $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000 ' or . = ' $1,000,000  $2,000,000  $3,000,000  $4,000,000  $5,000,000 ')]</value>
      <webElementGuid>44c29e90-14a6-444d-9a26-6a08ad3c1fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
