<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1,000,000  2,000,000_1</name>
   <tag></tag>
   <elementGuidId>ffe23e16-1ae1-4db6-9546-fa5640b8e139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULEBLEachEmpLimit-1233-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exULEBLEachEmpLimit-1233-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>53d0e646-db16-4e22-bf79-10ccad387ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULEBLArray_0_exULEBLEachEmpLimit</value>
      <webElementGuid>19dcb25e-8d1f-4b6c-9aea-474d69cd351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULEBLArray_0_exULEBLEachEmpLimit</value>
      <webElementGuid>c8f1cacd-b2d2-4341-92e8-40758cbca357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULEBLEachEmpLimit-1233-0</value>
      <webElementGuid>210238f0-6069-4827-8cac-2a768d331f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $1,000,000  $2,000,000 </value>
      <webElementGuid>4a777d6c-293c-41a3-8c9f-25f23598ee3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULEBLEachEmpLimit-1233-0&quot;)</value>
      <webElementGuid>7b40b5a8-580b-4f1c-b9a0-36ffa794d3fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exULEBLEachEmpLimit-1233-0']</value>
      <webElementGuid>6650e79a-dbc9-4096-a8db-8279f4bfe407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[3]/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>53abbd4c-2ecf-4166-94d4-2a8a25e8de18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Benefits Liability Each Employee'])[1]/following::select[1]</value>
      <webElementGuid>09a32fdd-ce36-4fbd-88b6-865c26807325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Benefits Liability Limits:'])[1]/following::select[1]</value>
      <webElementGuid>5d494b7a-9145-44b6-8b27-4388197f77c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Benefits Liability Aggregate'])[1]/preceding::select[1]</value>
      <webElementGuid>a5c18f9f-df59-4e00-8932-d80382305f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div/span/select</value>
      <webElementGuid>5ee13e1b-1409-438f-b568-028d8511187f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULEBLArray_0_exULEBLEachEmpLimit' and @id = 'field-exULEBLEachEmpLimit-1233-0' and (text() = ' $1,000,000  $2,000,000 ' or . = ' $1,000,000  $2,000,000 ')]</value>
      <webElementGuid>f9d92443-c3f3-4c90-8b90-aaf72ad47f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
