<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AL  AR  AZ  CA  CO  DC  DE  FL  GA  _6b5656</name>
   <tag></tag>
   <elementGuidId>5cb76768-5ecb-4aeb-a9d5-2c7d8fa97028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-policyHomeState-232</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-policyHomeState-232']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edbd0457-b1c9-41b6-b56f-83132d0171d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-policyHomeState</value>
      <webElementGuid>dfe21a38-b203-4174-9580-59b3684c21e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>policyHomeState</value>
      <webElementGuid>4b729c6f-7562-45cf-9861-f98f5ee18214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-policyHomeState-232</value>
      <webElementGuid>2b7420c6-cd04-4a32-a615-c32d1a443234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AL  AR  AZ  CA  CO  DC  DE  FL  GA  HI  IL  IN  KS  LA  MD  MI  MO  MS  NC  NE  NV  OH  OR  PA  SC  SD  TN  TX  VA  VT  WI  WY </value>
      <webElementGuid>f6f63cbc-802d-48ab-b916-bfc0ff43beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-policyHomeState-232&quot;)</value>
      <webElementGuid>9b356a87-fa73-4042-b685-45b8f3864347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-policyHomeState-232']</value>
      <webElementGuid>5e07c919-15bc-44ba-8268-886399aaa03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div[4]/div/div/div[2]/div/span/select</value>
      <webElementGuid>953b822e-bb8c-411c-b7b6-5e08e09fd1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Home State*'])[1]/following::select[1]</value>
      <webElementGuid>52175ec1-a32b-4391-af8e-74d69c040a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[2]/preceding::select[1]</value>
      <webElementGuid>e59e67d1-2b47-4743-bb05-03fb07ca316b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/span/select</value>
      <webElementGuid>a9f7d912-541f-4698-b292-b7b3e64b5a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'policyHomeState' and @id = 'field-policyHomeState-232' and (text() = ' AL  AR  AZ  CA  CO  DC  DE  FL  GA  HI  IL  IN  KS  LA  MD  MI  MO  MS  NC  NE  NV  OH  OR  PA  SC  SD  TN  TX  VA  VT  WI  WY ' or . = ' AL  AR  AZ  CA  CO  DC  DE  FL  GA  HI  IL  IN  KS  LA  MD  MI  MO  MS  NC  NE  NV  OH  OR  PA  SC  SD  TN  TX  VA  VT  WI  WY ')]</value>
      <webElementGuid>50882cc5-b835-4014-b3f0-b99c177c7929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
