<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Contractors  Truckers and Misc</name>
   <tag></tag>
   <elementGuidId>ed1e6871-611b-4b5b-8c6e-8f0a264be02f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exTruckSubclass-1146-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exTruckSubclass-1146-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c2e14bc4-0ab7-4351-ba62-65dd9d46521f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULALArray_0_exALLocation_1_exTruckSubclass</value>
      <webElementGuid>14cf3cfb-be4a-4277-8786-8e33587ca50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_1_exTruckSubclass</value>
      <webElementGuid>128beb76-4241-492f-839f-193c9bbd2b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exTruckSubclass-1146-1</value>
      <webElementGuid>2318371e-6168-48fe-9194-f3ee714534e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Contractors  Truckers and Misc </value>
      <webElementGuid>4432243d-e83b-4363-b4f9-b7b55cd082c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exTruckSubclass-1146-1&quot;)</value>
      <webElementGuid>b39690f9-6a48-4b3e-a324-e0d53576bbc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exTruckSubclass-1146-1']</value>
      <webElementGuid>755400dc-7321-4cc7-b8db-820b6511b9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div[2]/div/div/div[7]/div/div/div[2]/div/span/select</value>
      <webElementGuid>dd96f983-6588-41b2-9ea6-0846e14eab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Truck Subclass*'])[1]/following::select[1]</value>
      <webElementGuid>994b4303-625e-44b1-b837-a98f9d8305e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Radius Class*'])[1]/preceding::select[1]</value>
      <webElementGuid>29258f10-b26b-45a8-aaf8-5c4cb9509a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/span/select</value>
      <webElementGuid>4700b568-e0f8-44e7-a124-dccceece6eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULALArray_0_exALLocation_1_exTruckSubclass' and @id = 'field-exTruckSubclass-1146-1' and (text() = ' Contractors  Truckers and Misc ' or . = ' Contractors  Truckers and Misc ')]</value>
      <webElementGuid>6b9308e0-3380-4dcc-8ac4-d82fcaa6d3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
