<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1  Pa, Jeffersonville, IN, 47130,6  _f82e7e</name>
   <tag></tag>
   <elementGuidId>7efb2b0f-ebe8-4bd0-8ea1-4018bdadba67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-locationSelection-1062-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-locationSelection-1062-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0d5baed-5b00-4247-851d-280c2bf0b5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULGLArray_0_exGLLocation_0_locationSelection</value>
      <webElementGuid>684af121-3fba-4808-8bea-925a4b17735a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exGLLocation_0_locationSelection</value>
      <webElementGuid>fdec20f1-5595-482e-ab25-dd6482e1ea81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-locationSelection-1062-0</value>
      <webElementGuid>8b7b4f2d-9826-4cda-a210-1596bf21a5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1 => Pa, Jeffersonville, IN, 47130,6  2 => Page 100th, San Carlos, CA, 94070,12 </value>
      <webElementGuid>3cadd6d8-7082-488b-8d24-7004d1c6d47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-locationSelection-1062-0&quot;)</value>
      <webElementGuid>27dbb769-7e51-4733-a957-7b56627a3665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-locationSelection-1062-0']</value>
      <webElementGuid>ef0254ac-df12-433c-883b-0c0eeb29c856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[10]/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>eb2a2a34-d12f-42b0-89e0-27ba499b6e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Address*'])[1]/following::select[1]</value>
      <webElementGuid>12621581-e3a4-46c0-b242-9478b073b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#1'])[2]/following::select[1]</value>
      <webElementGuid>7bf9f32e-d7a4-4de4-9703-022fa09a92e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loc #*'])[1]/preceding::select[1]</value>
      <webElementGuid>e363d660-1dfb-4311-8c2c-58f94c2a9e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>a81ee28b-cb65-4286-8e28-a2ef34ea1555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULGLArray_0_exGLLocation_0_locationSelection' and @id = 'field-locationSelection-1062-0' and (text() = ' 1 => Pa, Jeffersonville, IN, 47130,6  2 => Page 100th, San Carlos, CA, 94070,12 ' or . = ' 1 => Pa, Jeffersonville, IN, 47130,6  2 => Page 100th, San Carlos, CA, 94070,12 ')]</value>
      <webElementGuid>313b2c53-5d26-4dbf-94f1-f7c9b6ebfeef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
