<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Susan Altrock  Antoinette Hardy-Many_5a52d7</name>
   <tag></tag>
   <elementGuidId>0031a47a-b880-43c8-a329-a5db71b678b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-underwriter-1218</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-underwriter-1218']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eda6afd2-f70e-4d4b-b6b0-ab281ceefc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-underwriter</value>
      <webElementGuid>592ea954-968c-4778-b001-90d516a840e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>underwriter</value>
      <webElementGuid>f34228a6-7571-46fa-989f-fa1f09fdfbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-underwriter-1218</value>
      <webElementGuid>3c04dd38-5a14-412c-939d-11984af9f0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Susan Altrock  Antoinette Hardy-Manyfield  Mike Burke </value>
      <webElementGuid>1f93ae85-5b85-4f01-9d07-8a25a29fdda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-underwriter-1218&quot;)</value>
      <webElementGuid>3585cd83-548f-4eb2-8fdd-3ea16e52f400</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-underwriter-1218']</value>
      <webElementGuid>02d43759-5b70-4b6b-8bfb-d5eaddfb1d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[20]/div/div[2]/div/div/div[2]/div/span/select</value>
      <webElementGuid>93f21dd7-7777-4a65-869a-d9b01241b3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter:'])[1]/following::select[1]</value>
      <webElementGuid>7e1176d1-dc02-4d8c-9e22-4d2fd28fb395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[1]/preceding::select[1]</value>
      <webElementGuid>6adcb964-1e00-42a1-a650-3c7b02099e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[2]/div/div/div[2]/div/span/select</value>
      <webElementGuid>97de9ec0-9976-4cb9-b82d-7f15db65fbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'underwriter' and @id = 'field-underwriter-1218' and (text() = ' Susan Altrock  Antoinette Hardy-Manyfield  Mike Burke ' or . = ' Susan Altrock  Antoinette Hardy-Manyfield  Mike Burke ')]</value>
      <webElementGuid>1582acc3-7215-4a00-a860-c5dd022ecda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
