<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Included  Excluded</name>
   <tag></tag>
   <elementGuidId>17b1bf99-12a1-4f14-9c8b-66b7a303372d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exTerrorism-1160</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exTerrorism-1160']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c505d9f-b334-4909-86fb-2287ef5848fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exTerrorism</value>
      <webElementGuid>c43f16c7-8be8-44b0-a3fa-8b48fd4ee467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exTerrorism</value>
      <webElementGuid>c58d1dbf-0ecf-4432-9c62-e56e2f6989a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exTerrorism-1160</value>
      <webElementGuid>4affc12f-f7b4-4b1d-b38e-1dd8b408da8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Included  Excluded </value>
      <webElementGuid>d86345f3-aa49-47f5-a847-dc267e9d12f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exTerrorism-1160&quot;)</value>
      <webElementGuid>5c7c573c-a1d0-4773-8c85-cc800308ce17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exTerrorism-1160']</value>
      <webElementGuid>e57d200a-bfb1-40fa-ab0d-f78c49234890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>cd33b20a-98f0-4f39-a35f-6a48cf453941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrorism'])[1]/following::select[1]</value>
      <webElementGuid>9710a6c1-ad4e-40de-81d0-a6d0c93fa099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excess Policy Limits:'])[1]/preceding::select[1]</value>
      <webElementGuid>8ff8a22a-84f8-4372-b030-55c08238ae56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>68451510-e4b5-4d37-bf43-2d95c41ce0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exTerrorism' and @id = 'field-exTerrorism-1160' and (text() = ' Included  Excluded ' or . = ' Included  Excluded ')]</value>
      <webElementGuid>027ae699-7bd2-4b59-b256-c0953017bae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
