<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  3,000,000  4,000,000  5,00_2fc9ab</name>
   <tag></tag>
   <elementGuidId>607b5e63-d950-4047-b4e5-e6837c1c0610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exULGLAggregateLimit-1048-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exULGLAggregateLimit-1048-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1cff6cf-91a8-430d-a5ac-d79e023ad1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULGLArray_0_exULGLAggregateLimit</value>
      <webElementGuid>25ac141c-e0bf-4964-961d-c8958ad59daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULGLArray_0_exULGLAggregateLimit</value>
      <webElementGuid>6714296c-6f77-4ac3-962a-c26f4740e47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exULGLAggregateLimit-1048-0</value>
      <webElementGuid>1c5c9abe-bab2-463e-abbf-e98ae1d49456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  $3,000,000  $4,000,000  $5,000,000  $6,000,000  $7,000,000  $8,000,000  $9,000,000  $10,000,000 </value>
      <webElementGuid>70c62a4d-f78b-4101-aae1-f78eb4d76b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exULGLAggregateLimit-1048-0&quot;)</value>
      <webElementGuid>96b2426f-42dc-4e12-9a71-d5993f3f795a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exULGLAggregateLimit-1048-0']</value>
      <webElementGuid>0da5d984-532a-4ed2-b891-cd024a14aca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[3]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div[2]/div/div/div[2]/div/span/select</value>
      <webElementGuid>15fc0ff3-4dfb-4f7e-a597-971961047959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Aggregate Limit*'])[1]/following::select[1]</value>
      <webElementGuid>dfbaf314-ec4e-4131-9a14-6e3a40b464f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products-Completed Operations Aggregate Limit*'])[1]/preceding::select[1]</value>
      <webElementGuid>0d2b55bd-d18d-45aa-9362-550ea7a62b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[2]/div/span/select</value>
      <webElementGuid>d90f6d2d-8d9b-4a12-9730-7161995bc72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULGLArray_0_exULGLAggregateLimit' and @id = 'field-exULGLAggregateLimit-1048-0' and (text() = ' (select)  $3,000,000  $4,000,000  $5,000,000  $6,000,000  $7,000,000  $8,000,000  $9,000,000  $10,000,000 ' or . = ' (select)  $3,000,000  $4,000,000  $5,000,000  $6,000,000  $7,000,000  $8,000,000  $9,000,000  $10,000,000 ')]</value>
      <webElementGuid>834bff51-26a8-45cb-bbd1-85438af8a372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
