<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1,000,000  2,000,000</name>
   <tag></tag>
   <elementGuidId>373c0a74-dcbe-4e19-b961-d2c3e31ce71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exHiredLimit-1137-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exHiredLimit-1137-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb173312-7f87-46ae-b02d-0344fb9564ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULALArray_0_exHiredLimit</value>
      <webElementGuid>8fb5ca0b-261d-43b8-bc9a-4214cabfd5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exHiredLimit</value>
      <webElementGuid>3b4575f9-2741-499d-a7d5-caddb959e0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exHiredLimit-1137-0</value>
      <webElementGuid>9a1673d5-383a-4b40-a276-6804f3e43f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $1,000,000  $2,000,000 </value>
      <webElementGuid>3907d522-0812-4c69-b40e-a820b0aa3f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exHiredLimit-1137-0&quot;)</value>
      <webElementGuid>99bac19f-2776-4eeb-8dac-3238f7da175a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exHiredLimit-1137-0']</value>
      <webElementGuid>eacd8e5a-d8f7-4971-ad64-3c183815eafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[5]/div/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>6f3b4454-0155-41d4-bfbb-b8a251be0fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired &amp; Non-Owned Auto Combined Single Limit'])[1]/following::select[1]</value>
      <webElementGuid>28448412-ceaf-4cfa-b45d-8a1341569c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired Auto Cost per Hire'])[1]/preceding::select[1]</value>
      <webElementGuid>71bdd160-93f9-4eb3-9af5-5e728b370190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>204b8e1d-a0e0-473c-8509-34203b7ce299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULALArray_0_exHiredLimit' and @id = 'field-exHiredLimit-1137-0' and (text() = ' $1,000,000  $2,000,000 ' or . = ' $1,000,000  $2,000,000 ')]</value>
      <webElementGuid>60c5dbf3-caac-4e2a-b53c-fc4eccef108c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
