<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Service  Retail  Commercial</name>
   <tag></tag>
   <elementGuidId>a4352c5e-1366-463b-b5cb-c72ae91a1496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exAutoBusinessUseClass-1143-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-exAutoBusinessUseClass-1143-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a604f9fb-38e5-42c4-bf35-8365a5c9b994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-exULALArray_0_exALLocation_1_exAutoBusinessUseClass</value>
      <webElementGuid>8c6036f3-abc2-4b12-92f1-e95bd5d55f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exULALArray_0_exALLocation_1_exAutoBusinessUseClass</value>
      <webElementGuid>e6448bc5-db65-40f8-a389-96e3391ce51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exAutoBusinessUseClass-1143-1</value>
      <webElementGuid>c0e39559-7bf8-49d2-8cfb-db56ef7c3827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Service  Retail  Commercial </value>
      <webElementGuid>2cba796f-12f6-4b13-98a5-dbed854ee227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exAutoBusinessUseClass-1143-1&quot;)</value>
      <webElementGuid>37208833-9180-49b2-9923-ee9f23beae5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-exAutoBusinessUseClass-1143-1']</value>
      <webElementGuid>d0477c60-1c32-4f57-910f-a0a6e149c0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div[2]/div/div/div[6]/div/div/div[2]/div/span/select</value>
      <webElementGuid>5f0c020d-0031-4a34-a5b5-69a617eb44aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Business Use Class*'])[1]/following::select[1]</value>
      <webElementGuid>905249ad-a178-4634-814c-f2e9a59b8e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Truck Subclass*'])[1]/preceding::select[1]</value>
      <webElementGuid>1fcf29ad-62e9-411c-a425-f594b36b9609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/span/select</value>
      <webElementGuid>ebff028e-af12-4954-90d3-07a762e9dba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'exULALArray_0_exALLocation_1_exAutoBusinessUseClass' and @id = 'field-exAutoBusinessUseClass-1143-1' and (text() = ' Service  Retail  Commercial ' or . = ' Service  Retail  Commercial ')]</value>
      <webElementGuid>1cbf90a3-2f4b-4b99-81b1-df24b8b8d3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
