<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2_icon ml-1</name>
   <tag></tag>
   <elementGuidId>7eb19b6b-bf4e-4a71-a9fd-650c37dbb1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card.item.item-2.collapsed > div.card-header > div.card-header-title > span.delete-icon > span.icon.ml-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div/div/span[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45b368b7-6308-4c57-9fda-dfde5c771291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>icon-name-Trash</value>
      <webElementGuid>a6b0ac5e-8563-4418-8986-be3c85c3234c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon ml-1</value>
      <webElementGuid>a402bfb4-f607-4542-bf2f-6e1d0d32fde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exULALPane horizontal&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;array box exULALArray column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-1&quot;]/div[@class=&quot;card-content not-columns&quot;]/div[@class=&quot;array box exALLocation not-column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-2 collapsed&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;card-header-title&quot;]/span[@class=&quot;delete-icon&quot;]/span[@class=&quot;icon ml-1&quot;]</value>
      <webElementGuid>a0dc10b2-8b2a-43a6-8934-f62e1e9a8e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[6]/div[3]/div[2]/div/div/span[3]/span</value>
      <webElementGuid>51b65863-a195-40f0-beb7-cbab441825bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#2'])[1]/following::span[15]</value>
      <webElementGuid>099d1811-76e9-4f4c-b9c5-838cf274818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FL'])[1]/following::span[22]</value>
      <webElementGuid>1927535e-a9a3-436f-89a2-61429b909595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#3'])[1]/preceding::span[1]</value>
      <webElementGuid>d632849f-dd24-4467-83c8-e90650357b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Code'])[1]/preceding::span[18]</value>
      <webElementGuid>c9ce14b4-fbe9-41b0-a495-7b820a6e384d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[3]/span</value>
      <webElementGuid>3f4d3197-478a-4968-b33e-d73013b01b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
