<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2</name>
   <tag></tag>
   <elementGuidId>31730a37-a188-46d9-9571-2d217373ab30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84f84e41-c90c-4e84-9b80-06d6c9adedf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>eacc199d-d82e-443c-a064-758d505db86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exULEBLPane horizontal&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;array box exULEBLArray column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-1&quot;]/div[@class=&quot;card-content not-columns&quot;]/div[@class=&quot;card is-paddingless group carrierInfo vertical&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;not-columns&quot;]/div[@class=&quot;group line3 horizontal&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;field-container exULEBLEffDate column&quot;]/div[@class=&quot;field schema-field&quot;]/div[@class=&quot;b-tooltip is-primary is-bottom is-medium is-multiline maybe-tooltip&quot;]/div[@class=&quot;tooltip-trigger&quot;]/div[@class=&quot;datepicker control is-small&quot;]/div[@class=&quot;dropdown dropdown-menu-animation is-bottom-right is-active is-mobile-modal&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;dropdown-content&quot;]/div[@class=&quot;dropdown-item&quot;]/div[1]/div[@class=&quot;datepicker-content&quot;]/section[@class=&quot;datepicker-table&quot;]/div[@class=&quot;datepicker-body&quot;]/div[@class=&quot;datepicker-row&quot;]/a[@class=&quot;datepicker-cell is-selectable&quot;]/span[1]</value>
      <webElementGuid>f53bd9e1-3d1c-41d0-82f6-4a39456699e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div/a[2]/span</value>
      <webElementGuid>eb5abfe9-3be0-4783-89ed-aeef2c87e29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[10]/following::span[7]</value>
      <webElementGuid>a9b34b84-4112-42d3-95e7-a9aff77deef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[5]/following::span[8]</value>
      <webElementGuid>4143f36c-aefa-415e-bd4f-b8a3352d3201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[3]/preceding::span[36]</value>
      <webElementGuid>4cfcebde-b976-4278-9c94-429d22cc0d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div[3]/div/div/div/div/section/div/div/a[2]/span</value>
      <webElementGuid>bd98d0c6-5a4b-4541-afd4-5404f051f9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2' or . = '2')]</value>
      <webElementGuid>312cba6f-5a65-4254-abbe-56b86bff9aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
