<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hired and Non-Owned Auto Coverage</name>
   <tag></tag>
   <elementGuidId>f6ba9630-e054-408e-a7e6-3fb789662ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div/div[2]/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e95e48c3-b634-4495-a07d-94809cb772fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>de146be0-56d3-4c54-83f1-601f0343f9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hired and Non-Owned Auto Coverage </value>
      <webElementGuid>454a3779-0779-435c-a019-aae5f1f09f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schema-form&quot;)/form[1]/div[@class=&quot;card is-paddingless group exULALPane horizontal&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;array box exULALArray column&quot;]/div[@class=&quot;scrollable pl-3 pb-4&quot;]/div[@class=&quot;card item item-1&quot;]/div[@class=&quot;card-content not-columns&quot;]/div[@class=&quot;group exHiredandNonOwnedYN horizontal&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;field-container exHiredYN column&quot;]/div[@class=&quot;field schema-field&quot;]/div[@class=&quot;b-tooltip is-primary is-bottom is-medium is-multiline maybe-tooltip&quot;]/div[@class=&quot;tooltip-trigger&quot;]/label[@class=&quot;checkbox is-small&quot;]/span[@class=&quot;control-label&quot;]</value>
      <webElementGuid>9941319c-5080-4ffb-abe7-d8ed6c421b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[4]/div/div/div/div/div[3]/div/div[2]/div[4]/div/div/div/div/div[2]/label/span[2]</value>
      <webElementGuid>b4d649ec-5938-4df6-82aa-a2b8efa9f03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underlying Auto Liability Premium*'])[1]/following::span[2]</value>
      <webElementGuid>c267cb94-64ad-497d-aa66-e2db8501159f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired &amp; Non-Owned Auto Combined Single Limit'])[1]/preceding::span[1]</value>
      <webElementGuid>36251c40-3106-48bb-8a51-d7c4a886c8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hired and Non-Owned Auto Coverage']/parent::*</value>
      <webElementGuid>9d8a79fb-3f1c-41c8-8361-89ada1318875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/label/span[2]</value>
      <webElementGuid>aca49578-7e2c-4ce2-9c05-fa221450eb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Hired and Non-Owned Auto Coverage ' or . = ' Hired and Non-Owned Auto Coverage ')]</value>
      <webElementGuid>1e6d39b2-9d2b-4173-a8e2-545c196533cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
