<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Layer 5-5M Excess_check</name>
   <tag></tag>
   <elementGuidId>b64a6062-8ab0-45dd-8ccd-c5ff2b27e8a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exLayer5MExcessSelection-1269 > span.check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='field-exLayer5MExcessSelection-1269']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8660bdc-8e38-4c29-a00e-01c202b2b71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>switch-check</value>
      <webElementGuid>c86ea43a-da77-4d1f-a240-b55b83fc9ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>c06a9b8b-efbd-4d60-a158-63d621d299bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exLayer5MExcessSelection-1269&quot;)/span[@class=&quot;check&quot;]</value>
      <webElementGuid>641165ad-d0b8-478c-9d37-a0f27dcb59d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='field-exLayer5MExcessSelection-1269']/span</value>
      <webElementGuid>556f5ae0-c27c-45bb-a113-ccb3b3fae071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/div/div/div[2]/label/span</value>
      <webElementGuid>880501a3-516c-44ab-8bb5-b6625803d3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
