<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Loss Experience_lossExperience</name>
   <tag></tag>
   <elementGuidId>5607f44b-cddb-43d7-b55e-d9e45d8960e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-lossExperience-1203</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field-lossExperience-1203']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d2fd1950-f412-4a2f-a14d-b32ba96a7af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-lossExperience-1203</value>
      <webElementGuid>202271cd-3f91-41f8-a5c0-cb476c8d0f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e74e9e84-4135-4103-969f-a05d8efcad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lossExperience</value>
      <webElementGuid>ed876d4a-817e-48fd-aa16-8950b8781f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea is-full-width</value>
      <webElementGuid>cbc401e8-240d-4c84-9c3c-d8c8d122ba28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-lossExperience-1203&quot;)</value>
      <webElementGuid>30e433f0-e199-4911-a648-bb6bfd3fbad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field-lossExperience-1203']</value>
      <webElementGuid>a28fe9a6-db9a-41e3-8444-e9914af9adfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[16]/div/div[2]/div/div/div[2]/div/textarea</value>
      <webElementGuid>d12109ff-f048-4448-a41f-d4a16e989ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div/div/div[2]/div/textarea</value>
      <webElementGuid>c609e709-ada9-4e09-b7df-aea076ead162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field-lossExperience-1203' and @name = 'lossExperience']</value>
      <webElementGuid>c660d6dc-62a2-42a0-ad29-ec8cfc0289d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
