<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Add  Employers  Liability  Policy__be5c1a</name>
   <tag></tag>
   <elementGuidId>906e8823-b726-45e3-a8e7-410d496bcf5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-exUWNotes-1221</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field-exUWNotes-1221']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5ebd538c-4903-4e13-a992-45233495250f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-exUWNotes-1221</value>
      <webElementGuid>0611952c-4bf1-4cff-8e6d-a1dc0b90d9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>60441d36-81fc-4f46-905d-fd4f47f0f80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exUWNotes</value>
      <webElementGuid>96515719-6041-496b-9d34-4c7d164aa98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea is-full-width</value>
      <webElementGuid>0c6d869e-0031-4934-a243-adf7f2654f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-exUWNotes-1221&quot;)</value>
      <webElementGuid>8f81f3c1-fc7e-4dea-ba0c-9f1a57c3e63c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field-exUWNotes-1221']</value>
      <webElementGuid>4eb4c041-20dd-434c-93e4-35d1704eba88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[7]/div/div/div/div/div/div/div[2]/div/textarea</value>
      <webElementGuid>4ae122a9-9dcf-4326-bd7a-2374ab8dab45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4c3a8abf-7f9d-4e74-b8d4-7fe26646bd9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field-exUWNotes-1221' and @name = 'exUWNotes']</value>
      <webElementGuid>b301e250-ee67-4d90-848c-5e7c03ca44ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
