<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Company Representative_insuredAgent</name>
   <tag></tag>
   <elementGuidId>9b9c182e-a33c-4a5c-9f31-65b5cab35947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-insuredAgent-1212</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field-insuredAgent-1212']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fdf6d50e-62fc-4352-9699-3c94bcdb5527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-insuredAgent-1212</value>
      <webElementGuid>cb989c3c-3413-4e98-9b2b-b785b80b1c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>77a0c378-5267-4aa3-9eb6-1c6f9fc0e43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insuredAgent</value>
      <webElementGuid>dbc4f1ca-3218-4c61-ab55-50d61076042d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1d16dd72-1658-4d26-8ea6-dad5ba081e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-insuredAgent-1212&quot;)</value>
      <webElementGuid>bb6ec324-5935-42be-8572-664a15f76cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field-insuredAgent-1212']</value>
      <webElementGuid>ba3c2d7a-9da4-462a-a5d7-73d4764cc938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[19]/div/div/div/div/div[2]/div/textarea</value>
      <webElementGuid>c233d1a1-2315-4e95-b75c-dfdd1590f0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div/div/div[2]/div/textarea</value>
      <webElementGuid>c3e74333-95f4-439c-8360-c7db084387ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field-insuredAgent-1212' and @name = 'insuredAgent']</value>
      <webElementGuid>668f48af-1817-47a8-ad78-02b1c769fb74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
