<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_concat(  , , required, ,  true)_no_87b019</name>
   <tag></tag>
   <elementGuidId>c73ff217-2390-4076-b81d-bba3e546ec48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-notesRatingRational-1211</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field-notesRatingRational-1211']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>49da9efa-425c-4d9f-b96e-7352d81f732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-notesRatingRational-1211</value>
      <webElementGuid>1da87a69-5c96-4774-abc6-5d72bcdca4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7cecbb89-83fb-40af-a0e9-7214b21b1529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notesRatingRational</value>
      <webElementGuid>0d312fb0-1efb-4cd4-b469-14a73a4214d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea is-full-width</value>
      <webElementGuid>e3f18151-5728-40cb-ba8d-c565d01f9bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-notesRatingRational-1211&quot;)</value>
      <webElementGuid>06afdfa1-82fe-4d0b-99f7-9f9ad549e3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field-notesRatingRational-1211']</value>
      <webElementGuid>c3ea8221-6b3c-4c18-add1-34ad93833926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[17]/div/div/div/div[3]/div/div[2]/div/div/div[2]/div/textarea</value>
      <webElementGuid>b7134b05-7059-49e1-82b8-8e5f4951666c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]/div/textarea</value>
      <webElementGuid>390b63bf-fcca-40c9-87d1-c0633370ad13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field-notesRatingRational-1211' and @name = 'notesRatingRational']</value>
      <webElementGuid>5b6323be-9b26-4853-a27f-ee73f866057f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
