<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Auto Summary_autoSummary</name>
   <tag></tag>
   <elementGuidId>dc3ccac7-05fe-43a1-854e-4eac774a9f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-autoSummary-1201</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field-autoSummary-1201']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ebc55255-afdd-4fe0-b11c-50ad5f3dc7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-autoSummary-1201</value>
      <webElementGuid>56387bbe-2581-4d79-933a-16ff17b8fbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>54305f93-0bc2-4def-9594-b415cff9c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autoSummary</value>
      <webElementGuid>4de3867b-bc64-4970-8362-e83a760afb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea is-full-width</value>
      <webElementGuid>0dc2546c-52ae-4596-a10d-bd220d946002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-autoSummary-1201&quot;)</value>
      <webElementGuid>e8ee1a7d-c6e1-47b9-b81b-4f6f41f99b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field-autoSummary-1201']</value>
      <webElementGuid>bdc385fd-6621-4e27-8082-7aad825e2969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div/div/div/div/div[15]/div/div[2]/div/div/div[2]/div/textarea</value>
      <webElementGuid>09d0220d-f895-4dd2-9032-5dcceed91eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b08bda72-a516-48b5-b0b1-06196f321a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field-autoSummary-1201' and @name = 'autoSummary']</value>
      <webElementGuid>040ebdb7-1082-4050-8395-be5fe295496d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
