<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Doing Business As (DBA)_dbaName</name>
   <tag></tag>
   <elementGuidId>4bcc00e0-d7ed-453d-9ba9-b7424f50488f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-dbaName-251</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-dbaName-251']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb51e3c-e298-47a5-86e8-400793b66163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-dbaName-251</value>
      <webElementGuid>8898459c-7693-4fbd-aa8e-f83d4063c01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dbaName</value>
      <webElementGuid>3338ab2e-ca68-42db-9ad1-a2f79c046d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-dbaName-251</value>
      <webElementGuid>61adce81-4d16-4e6d-a472-8e05c3053e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small is-full-width</value>
      <webElementGuid>6e23f893-6059-41de-bdb3-4f3a2ca884b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-dbaName-251&quot;)</value>
      <webElementGuid>74c981ca-4294-4a7c-804d-afb3daaa6209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-dbaName-251']</value>
      <webElementGuid>eda36b3f-8120-4465-929f-6859d30ffe5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[4]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>d1f9d40e-2807-4bba-9a27-95f9c691e2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a4337691-8dcf-4cad-9c78-a347f9b6924c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-dbaName-251' and @name = 'dbaName']</value>
      <webElementGuid>8ee58dc1-985d-4652-8f6a-01bc24b30875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
