<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter account name up to 100 characte_f995ea</name>
   <tag></tag>
   <elementGuidId>3181a4ca-a57f-4ef7-9056-41a1f3da9395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-accountName-244</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-accountName-244']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00492b73-94b4-4de1-9950-8c8ed29fefcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-accountName-244</value>
      <webElementGuid>73e8a74a-4374-40ed-be43-9ab0eb651d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountName</value>
      <webElementGuid>24a9d52f-a621-47d6-b45b-5234444377cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>field-field-accountName-244</value>
      <webElementGuid>99f93db9-e036-4b53-8678-67e723987a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-small is-full-width</value>
      <webElementGuid>3c6674b8-fdb3-4613-b52e-b175eb7dfc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-accountName-244&quot;)</value>
      <webElementGuid>a1120464-5f7f-42c9-84c8-91c0c531bbe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-accountName-244']</value>
      <webElementGuid>8ebf20b0-91fd-462a-a47e-5661a981c7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>c812074e-ebea-467d-915e-de1146b63d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>f29c88e1-13f9-414a-a41c-3d32e2456ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-accountName-244' and @name = 'accountName']</value>
      <webElementGuid>c53a1edb-feb7-4092-a30d-8863809f51eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
