<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Corporation  Individual  Joint Ventu_c631ef</name>
   <tag></tag>
   <elementGuidId>5045c31f-2c4c-4e5f-9130-06c65cea95f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-formOfBusiness-243</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='field-formOfBusiness-243']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de293f58-8080-4e7e-8527-dbbd5fd109e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>basic-select-formOfBusiness</value>
      <webElementGuid>dd6de316-e8f9-467d-bf0b-63f9a086f29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formOfBusiness</value>
      <webElementGuid>63920202-87ba-41a4-b386-199114afb000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-formOfBusiness-243</value>
      <webElementGuid>04818b9e-873e-433a-bf96-0cd690ac3294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Corporation  Individual  Joint Venture  Limited Liability Co. (LLC)  Other  Partnership  Trust </value>
      <webElementGuid>c8e5adb7-a8c5-4dc3-953a-6dad0a15a6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-formOfBusiness-243&quot;)</value>
      <webElementGuid>3e598677-efff-4c5b-aef0-c42c6f9934c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='field-formOfBusiness-243']</value>
      <webElementGuid>b04b8472-e59d-4e5f-84bb-3703df945920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schema-form']/form/div[2]/div/div/div/div[5]/div/div[7]/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>3536db7c-a5a0-4e25-9c2e-201ea4528c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form of Business*'])[1]/following::select[1]</value>
      <webElementGuid>3dcdf5c2-5904-4758-868b-46d48c008a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Number'])[1]/preceding::select[1]</value>
      <webElementGuid>aa631a7f-1959-4b5d-8949-3a70d3456329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/span/select</value>
      <webElementGuid>67415134-d641-4039-9f91-51fce78d9cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'formOfBusiness' and @id = 'field-formOfBusiness-243' and (text() = ' Corporation  Individual  Joint Venture  Limited Liability Co. (LLC)  Other  Partnership  Trust ' or . = ' Corporation  Individual  Joint Venture  Limited Liability Co. (LLC)  Other  Partnership  Trust ')]</value>
      <webElementGuid>14019555-e7e3-4426-850f-ffdbc3db5ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
